// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proof.proto

package crypto

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProofProto struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LeafHash             []byte   `protobuf:"bytes,3,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Aunts                [][]byte `protobuf:"bytes,4,rep,name=aunts,proto3" json:"aunts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofProto) Reset()         { *m = ProofProto{} }
func (m *ProofProto) String() string { return proto.CompactTextString(m) }
func (*ProofProto) ProtoMessage()    {}
func (*ProofProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_473d204b28f447f0, []int{0}
}

func (m *ProofProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofProto.Unmarshal(m, b)
}
func (m *ProofProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofProto.Marshal(b, m, deterministic)
}
func (m *ProofProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofProto.Merge(m, src)
}
func (m *ProofProto) XXX_Size() int {
	return xxx_messageInfo_ProofProto.Size(m)
}
func (m *ProofProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProofProto proto.InternalMessageInfo

func (m *ProofProto) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ProofProto) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ProofProto) GetLeafHash() []byte {
	if m != nil {
		return m.LeafHash
	}
	return nil
}

func (m *ProofProto) GetAunts() [][]byte {
	if m != nil {
		return m.Aunts
	}
	return nil
}

type ValueOpProto struct {
	// Encoded in ProofOp.Key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// To encode in ProofOp.Data
	Proof                *ProofProto `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ValueOpProto) Reset()         { *m = ValueOpProto{} }
func (m *ValueOpProto) String() string { return proto.CompactTextString(m) }
func (*ValueOpProto) ProtoMessage()    {}
func (*ValueOpProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_473d204b28f447f0, []int{1}
}

func (m *ValueOpProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueOpProto.Unmarshal(m, b)
}
func (m *ValueOpProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueOpProto.Marshal(b, m, deterministic)
}
func (m *ValueOpProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueOpProto.Merge(m, src)
}
func (m *ValueOpProto) XXX_Size() int {
	return xxx_messageInfo_ValueOpProto.Size(m)
}
func (m *ValueOpProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueOpProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValueOpProto proto.InternalMessageInfo

func (m *ValueOpProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ValueOpProto) GetProof() *ProofProto {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DominoOpProto struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Input                string   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DominoOpProto) Reset()         { *m = DominoOpProto{} }
func (m *DominoOpProto) String() string { return proto.CompactTextString(m) }
func (*DominoOpProto) ProtoMessage()    {}
func (*DominoOpProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_473d204b28f447f0, []int{2}
}

func (m *DominoOpProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DominoOpProto.Unmarshal(m, b)
}
func (m *DominoOpProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DominoOpProto.Marshal(b, m, deterministic)
}
func (m *DominoOpProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DominoOpProto.Merge(m, src)
}
func (m *DominoOpProto) XXX_Size() int {
	return xxx_messageInfo_DominoOpProto.Size(m)
}
func (m *DominoOpProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DominoOpProto.DiscardUnknown(m)
}

var xxx_messageInfo_DominoOpProto proto.InternalMessageInfo

func (m *DominoOpProto) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DominoOpProto) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *DominoOpProto) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

// ProofOp defines an operation used for calculating Merkle root
// The data could be arbitrary format, providing nessecary data
// for example neighbouring node hash
type ProofOpProto struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofOpProto) Reset()         { *m = ProofOpProto{} }
func (m *ProofOpProto) String() string { return proto.CompactTextString(m) }
func (*ProofOpProto) ProtoMessage()    {}
func (*ProofOpProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_473d204b28f447f0, []int{3}
}

func (m *ProofOpProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOpProto.Unmarshal(m, b)
}
func (m *ProofOpProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOpProto.Marshal(b, m, deterministic)
}
func (m *ProofOpProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOpProto.Merge(m, src)
}
func (m *ProofOpProto) XXX_Size() int {
	return xxx_messageInfo_ProofOpProto.Size(m)
}
func (m *ProofOpProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOpProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOpProto proto.InternalMessageInfo

func (m *ProofOpProto) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProofOpProto) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProofOpProto) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ProofOps is Merkle proof defined by the list of ProofOps
type ProofOpsProto struct {
	Ops                  []*ProofOpProto `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProofOpsProto) Reset()         { *m = ProofOpsProto{} }
func (m *ProofOpsProto) String() string { return proto.CompactTextString(m) }
func (*ProofOpsProto) ProtoMessage()    {}
func (*ProofOpsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_473d204b28f447f0, []int{4}
}

func (m *ProofOpsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOpsProto.Unmarshal(m, b)
}
func (m *ProofOpsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOpsProto.Marshal(b, m, deterministic)
}
func (m *ProofOpsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOpsProto.Merge(m, src)
}
func (m *ProofOpsProto) XXX_Size() int {
	return xxx_messageInfo_ProofOpsProto.Size(m)
}
func (m *ProofOpsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOpsProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOpsProto proto.InternalMessageInfo

func (m *ProofOpsProto) GetOps() []*ProofOpProto {
	if m != nil {
		return m.Ops
	}
	return nil
}

func init() {
	proto.RegisterType((*ProofProto)(nil), "tendermint.crypto.ProofProto")
	proto.RegisterType((*ValueOpProto)(nil), "tendermint.crypto.ValueOpProto")
	proto.RegisterType((*DominoOpProto)(nil), "tendermint.crypto.DominoOpProto")
	proto.RegisterType((*ProofOpProto)(nil), "tendermint.crypto.ProofOpProto")
	proto.RegisterType((*ProofOpsProto)(nil), "tendermint.crypto.ProofOpsProto")
}

func init() { proto.RegisterFile("proof.proto", fileDescriptor_473d204b28f447f0) }

var fileDescriptor_473d204b28f447f0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x6b, 0xab, 0x40,
	0x14, 0xc5, 0x9f, 0xd1, 0x84, 0x97, 0x1b, 0x03, 0xef, 0x49, 0x28, 0xd2, 0x52, 0x22, 0xae, 0xdc,
	0x54, 0x21, 0x59, 0x74, 0x55, 0x0a, 0xa1, 0x8b, 0xec, 0x12, 0x84, 0x76, 0xd1, 0x4d, 0x19, 0xe3,
	0xf8, 0x87, 0x18, 0x67, 0x98, 0x19, 0xa1, 0x7e, 0xc3, 0x7e, 0x8a, 0x7e, 0x96, 0x32, 0x77, 0x0c,
	0x59, 0xb4, 0x5d, 0x79, 0xcf, 0x71, 0xee, 0xef, 0xcc, 0x51, 0x98, 0x71, 0xc1, 0x58, 0x11, 0x73,
	0xc1, 0x14, 0xf3, 0xfe, 0x2b, 0xda, 0xe6, 0x54, 0x9c, 0xea, 0x56, 0xc5, 0x07, 0xd1, 0x73, 0xc5,
	0xae, 0x17, 0x25, 0x2b, 0x19, 0xbe, 0x4d, 0xf4, 0x64, 0x0e, 0x86, 0x47, 0x80, 0xbd, 0xde, 0xdb,
	0xe3, 0xda, 0x02, 0xc6, 0x8a, 0x29, 0xd2, 0xf8, 0x56, 0x60, 0x45, 0x76, 0x6a, 0x84, 0x76, 0xeb,
	0x36, 0xa7, 0xef, 0xfe, 0xc8, 0xb8, 0x28, 0xbc, 0x1b, 0x98, 0x36, 0x94, 0x14, 0x6f, 0x15, 0x91,
	0x95, 0x6f, 0x07, 0x56, 0xe4, 0xa6, 0x7f, 0xb5, 0xb1, 0x25, 0xb2, 0xd2, 0x2b, 0xa4, 0x6b, 0x95,
	0xf4, 0x9d, 0xc0, 0x8e, 0xdc, 0xd4, 0x88, 0xf0, 0x19, 0xdc, 0x17, 0xd2, 0x74, 0x74, 0xc7, 0x4d,
	0xdc, 0x3f, 0xb0, 0x8f, 0xb4, 0xc7, 0x30, 0x37, 0xd5, 0xa3, 0xb7, 0x86, 0x31, 0xd6, 0xc0, 0xa8,
	0xd9, 0xea, 0x36, 0xfe, 0xd6, 0x23, 0xbe, 0x5c, 0x37, 0x35, 0x67, 0xc3, 0x1d, 0xcc, 0x9f, 0xd8,
	0xa9, 0x6e, 0xd9, 0x0f, 0xdc, 0xa9, 0xe1, 0x62, 0x05, 0xde, 0x29, 0xe4, 0x4e, 0x53, 0x23, 0xbc,
	0x2b, 0x98, 0xb0, 0x4e, 0x69, 0xdb, 0x46, 0x7b, 0x50, 0xe1, 0x16, 0x5c, 0x4c, 0x39, 0xf3, 0x3c,
	0x70, 0x54, 0xcf, 0xe9, 0x00, 0xc4, 0xf9, 0x9c, 0x31, 0xba, 0xdc, 0xdd, 0x03, 0x27, 0x27, 0x8a,
	0x0c, 0xdf, 0x02, 0xe7, 0x70, 0x0b, 0xf3, 0x81, 0x24, 0x0d, 0xea, 0x1e, 0x6c, 0xc6, 0xa5, 0x6f,
	0x05, 0x76, 0x34, 0x5b, 0x2d, 0x7f, 0xab, 0x37, 0x04, 0x6f, 0x9c, 0x8f, 0xcf, 0xe5, 0x9f, 0x54,
	0x6f, 0x6c, 0x1e, 0x5f, 0x1f, 0xca, 0x5a, 0x55, 0x5d, 0x16, 0x1f, 0xd8, 0x29, 0xa9, 0x7a, 0x4e,
	0x45, 0x43, 0xf3, 0x92, 0x8a, 0xa4, 0x20, 0x99, 0xa8, 0x0f, 0x77, 0xb9, 0x60, 0xbc, 0xa9, 0xb3,
	0x04, 0xff, 0xab, 0x34, 0x8f, 0xac, 0x2b, 0x64, 0x62, 0xc0, 0xd9, 0x04, 0x9d, 0xf5, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xdf, 0xa2, 0x8e, 0x33, 0x28, 0x02, 0x00, 0x00,
}
