// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package bits

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BitArrayProto struct {
	Bits                 int64    `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	Elems                []uint64 `protobuf:"varint,2,rep,packed,name=elems,proto3" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BitArrayProto) Reset()         { *m = BitArrayProto{} }
func (m *BitArrayProto) String() string { return proto.CompactTextString(m) }
func (*BitArrayProto) ProtoMessage()    {}
func (*BitArrayProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *BitArrayProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BitArrayProto.Unmarshal(m, b)
}
func (m *BitArrayProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BitArrayProto.Marshal(b, m, deterministic)
}
func (m *BitArrayProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitArrayProto.Merge(m, src)
}
func (m *BitArrayProto) XXX_Size() int {
	return xxx_messageInfo_BitArrayProto.Size(m)
}
func (m *BitArrayProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BitArrayProto.DiscardUnknown(m)
}

var xxx_messageInfo_BitArrayProto proto.InternalMessageInfo

func (m *BitArrayProto) GetBits() int64 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *BitArrayProto) GetElems() []uint64 {
	if m != nil {
		return m.Elems
	}
	return nil
}

func init() {
	proto.RegisterType((*BitArrayProto)(nil), "tendermint.libs.bits.BitArrayProto")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x24, 0x8d, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0xc6, 0x83, 0xa0, 0x43, 0x8d, 0x0b, 0x61, 0x60, 0x24, 0x4e, 0x2c, 0xb6, 0x83, 0x89, 0xd1,
	0x51, 0x9e, 0xc0, 0x30, 0xba, 0x71, 0x70, 0xc2, 0x25, 0x85, 0x36, 0xd7, 0x73, 0xe0, 0xed, 0x0d,
	0x75, 0xfb, 0xfe, 0xe5, 0xfb, 0xa9, 0xa3, 0xac, 0x1e, 0x83, 0xf6, 0xec, 0xc4, 0xe5, 0x85, 0xe0,
	0x32, 0x20, 0xcf, 0xb4, 0x88, 0xb6, 0x04, 0x41, 0x03, 0x49, 0x38, 0x3f, 0xd4, 0xa9, 0x21, 0x79,
	0x32, 0x77, 0xeb, 0x2b, 0xce, 0x72, 0x95, 0x6d, 0x45, 0x99, 0x54, 0x49, 0x9d, 0xb6, 0x51, 0xe7,
	0x85, 0xda, 0xa3, 0xc5, 0x39, 0x94, 0xbb, 0x2a, 0xad, 0xb3, 0xf6, 0x6f, 0x9a, 0xfb, 0xfb, 0x36,
	0x92, 0x4c, 0x5f, 0xd0, 0xbd, 0x9b, 0xcd, 0xb4, 0x7a, 0x64, 0x8b, 0xc3, 0x88, 0x6c, 0x3e, 0x1d,
	0x30, 0xf5, 0x97, 0x81, 0x9d, 0xb7, 0x04, 0x26, 0xf2, 0x83, 0xd9, 0xa0, 0x66, 0xfb, 0x83, 0x43,
	0x4c, 0xae, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x48, 0xe8, 0x44, 0xa0, 0x00, 0x00, 0x00,
}
