// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package consensus

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	bits "github.com/hyperledger/fabric-droplib/protos/libs/bits"
	types "github.com/hyperledger/fabric-droplib/protos/protobufs/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageProtoWrapper struct {
	// Types that are valid to be assigned to Sum:
	//	*MessageProtoWrapper_Vote
	//	*MessageProtoWrapper_VoteSetMaj23
	Sum                  isMessageProtoWrapper_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MessageProtoWrapper) Reset()         { *m = MessageProtoWrapper{} }
func (m *MessageProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*MessageProtoWrapper) ProtoMessage()    {}
func (*MessageProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *MessageProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProtoWrapper.Unmarshal(m, b)
}
func (m *MessageProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProtoWrapper.Marshal(b, m, deterministic)
}
func (m *MessageProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProtoWrapper.Merge(m, src)
}
func (m *MessageProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_MessageProtoWrapper.Size(m)
}
func (m *MessageProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProtoWrapper proto.InternalMessageInfo

type isMessageProtoWrapper_Sum interface {
	isMessageProtoWrapper_Sum()
}

type MessageProtoWrapper_Vote struct {
	Vote *VoteProtoWrapper `protobuf:"bytes,6,opt,name=vote,proto3,oneof"`
}

type MessageProtoWrapper_VoteSetMaj23 struct {
	VoteSetMaj23 *VoteSetMaj23ProtoWrapper `protobuf:"bytes,8,opt,name=vote_set_maj23,json=voteSetMaj23,proto3,oneof"`
}

func (*MessageProtoWrapper_Vote) isMessageProtoWrapper_Sum() {}

func (*MessageProtoWrapper_VoteSetMaj23) isMessageProtoWrapper_Sum() {}

func (m *MessageProtoWrapper) GetSum() isMessageProtoWrapper_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *MessageProtoWrapper) GetVote() *VoteProtoWrapper {
	if x, ok := m.GetSum().(*MessageProtoWrapper_Vote); ok {
		return x.Vote
	}
	return nil
}

func (m *MessageProtoWrapper) GetVoteSetMaj23() *VoteSetMaj23ProtoWrapper {
	if x, ok := m.GetSum().(*MessageProtoWrapper_VoteSetMaj23); ok {
		return x.VoteSetMaj23
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageProtoWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageProtoWrapper_Vote)(nil),
		(*MessageProtoWrapper_VoteSetMaj23)(nil),
	}
}

type ProposalProtoWrapper struct {
	Proposal *types.ProposalProto `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	// 额外的字段,如果为SIGNED_MSG_TYPE_PROPOSAL,则还携带了block数据信息,移除block part 数据信息
	ExtraData            []byte   `protobuf:"bytes,8,opt,name=extraData,proto3" json:"extraData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalProtoWrapper) Reset()         { *m = ProposalProtoWrapper{} }
func (m *ProposalProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*ProposalProtoWrapper) ProtoMessage()    {}
func (*ProposalProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *ProposalProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalProtoWrapper.Unmarshal(m, b)
}
func (m *ProposalProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalProtoWrapper.Marshal(b, m, deterministic)
}
func (m *ProposalProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalProtoWrapper.Merge(m, src)
}
func (m *ProposalProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_ProposalProtoWrapper.Size(m)
}
func (m *ProposalProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalProtoWrapper proto.InternalMessageInfo

func (m *ProposalProtoWrapper) GetProposal() *types.ProposalProto {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func (m *ProposalProtoWrapper) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type ProposalPOLProtoWrapper struct {
	Height               int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ProposalPolRound     int32               `protobuf:"varint,2,opt,name=proposal_pol_round,json=proposalPolRound,proto3" json:"proposal_pol_round,omitempty"`
	ProposalPol          *bits.BitArrayProto `protobuf:"bytes,3,opt,name=proposal_pol,json=proposalPol,proto3" json:"proposal_pol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProposalPOLProtoWrapper) Reset()         { *m = ProposalPOLProtoWrapper{} }
func (m *ProposalPOLProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*ProposalPOLProtoWrapper) ProtoMessage()    {}
func (*ProposalPOLProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *ProposalPOLProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalPOLProtoWrapper.Unmarshal(m, b)
}
func (m *ProposalPOLProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalPOLProtoWrapper.Marshal(b, m, deterministic)
}
func (m *ProposalPOLProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalPOLProtoWrapper.Merge(m, src)
}
func (m *ProposalPOLProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_ProposalPOLProtoWrapper.Size(m)
}
func (m *ProposalPOLProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalPOLProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalPOLProtoWrapper proto.InternalMessageInfo

func (m *ProposalPOLProtoWrapper) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProposalPOLProtoWrapper) GetProposalPolRound() int32 {
	if m != nil {
		return m.ProposalPolRound
	}
	return 0
}

func (m *ProposalPOLProtoWrapper) GetProposalPol() *bits.BitArrayProto {
	if m != nil {
		return m.ProposalPol
	}
	return nil
}

type VoteProtoWrapper struct {
	Vote                 *types.VoteProto `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VoteProtoWrapper) Reset()         { *m = VoteProtoWrapper{} }
func (m *VoteProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*VoteProtoWrapper) ProtoMessage()    {}
func (*VoteProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *VoteProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteProtoWrapper.Unmarshal(m, b)
}
func (m *VoteProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteProtoWrapper.Marshal(b, m, deterministic)
}
func (m *VoteProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteProtoWrapper.Merge(m, src)
}
func (m *VoteProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_VoteProtoWrapper.Size(m)
}
func (m *VoteProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_VoteProtoWrapper proto.InternalMessageInfo

func (m *VoteProtoWrapper) GetVote() *types.VoteProto {
	if m != nil {
		return m.Vote
	}
	return nil
}

type NewRoundStepProtoWrapper struct {
	NewRoundStep         *types.NewRoundStepProto `protobuf:"bytes,1,opt,name=new_round_step,json=newRoundStep,proto3" json:"new_round_step,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NewRoundStepProtoWrapper) Reset()         { *m = NewRoundStepProtoWrapper{} }
func (m *NewRoundStepProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*NewRoundStepProtoWrapper) ProtoMessage()    {}
func (*NewRoundStepProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *NewRoundStepProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoundStepProtoWrapper.Unmarshal(m, b)
}
func (m *NewRoundStepProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoundStepProtoWrapper.Marshal(b, m, deterministic)
}
func (m *NewRoundStepProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoundStepProtoWrapper.Merge(m, src)
}
func (m *NewRoundStepProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_NewRoundStepProtoWrapper.Size(m)
}
func (m *NewRoundStepProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoundStepProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoundStepProtoWrapper proto.InternalMessageInfo

func (m *NewRoundStepProtoWrapper) GetNewRoundStep() *types.NewRoundStepProto {
	if m != nil {
		return m.NewRoundStep
	}
	return nil
}

type VoteSetMaj23ProtoWrapper struct {
	VoteSetMaj23         *types.VoteSetMaj23Proto `protobuf:"bytes,1,opt,name=vote_set_maj23,json=voteSetMaj23,proto3" json:"vote_set_maj23,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *VoteSetMaj23ProtoWrapper) Reset()         { *m = VoteSetMaj23ProtoWrapper{} }
func (m *VoteSetMaj23ProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*VoteSetMaj23ProtoWrapper) ProtoMessage()    {}
func (*VoteSetMaj23ProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *VoteSetMaj23ProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSetMaj23ProtoWrapper.Unmarshal(m, b)
}
func (m *VoteSetMaj23ProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSetMaj23ProtoWrapper.Marshal(b, m, deterministic)
}
func (m *VoteSetMaj23ProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSetMaj23ProtoWrapper.Merge(m, src)
}
func (m *VoteSetMaj23ProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_VoteSetMaj23ProtoWrapper.Size(m)
}
func (m *VoteSetMaj23ProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSetMaj23ProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSetMaj23ProtoWrapper proto.InternalMessageInfo

func (m *VoteSetMaj23ProtoWrapper) GetVoteSetMaj23() *types.VoteSetMaj23Proto {
	if m != nil {
		return m.VoteSetMaj23
	}
	return nil
}

type NewValidBlockProtoWrapper struct {
	Height               int64                     `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32                     `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	BlockPartSetHeader   *types.PartSetHeaderProto `protobuf:"bytes,3,opt,name=block_part_set_header,json=blockPartSetHeader,proto3" json:"block_part_set_header,omitempty"`
	BlockParts           *bits.BitArrayProto       `protobuf:"bytes,4,opt,name=block_parts,json=blockParts,proto3" json:"block_parts,omitempty"`
	IsCommit             bool                      `protobuf:"varint,5,opt,name=is_commit,json=isCommit,proto3" json:"is_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NewValidBlockProtoWrapper) Reset()         { *m = NewValidBlockProtoWrapper{} }
func (m *NewValidBlockProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*NewValidBlockProtoWrapper) ProtoMessage()    {}
func (*NewValidBlockProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *NewValidBlockProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewValidBlockProtoWrapper.Unmarshal(m, b)
}
func (m *NewValidBlockProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewValidBlockProtoWrapper.Marshal(b, m, deterministic)
}
func (m *NewValidBlockProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewValidBlockProtoWrapper.Merge(m, src)
}
func (m *NewValidBlockProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_NewValidBlockProtoWrapper.Size(m)
}
func (m *NewValidBlockProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_NewValidBlockProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_NewValidBlockProtoWrapper proto.InternalMessageInfo

func (m *NewValidBlockProtoWrapper) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NewValidBlockProtoWrapper) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *NewValidBlockProtoWrapper) GetBlockPartSetHeader() *types.PartSetHeaderProto {
	if m != nil {
		return m.BlockPartSetHeader
	}
	return nil
}

func (m *NewValidBlockProtoWrapper) GetBlockParts() *bits.BitArrayProto {
	if m != nil {
		return m.BlockParts
	}
	return nil
}

func (m *NewValidBlockProtoWrapper) GetIsCommit() bool {
	if m != nil {
		return m.IsCommit
	}
	return false
}

// HasVote is sent to indicate that a particular vote has been received.
type HasVoteProtoWrapper struct {
	Height               int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 types.SignedMsgType `protobuf:"varint,3,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	Index                int32               `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HasVoteProtoWrapper) Reset()         { *m = HasVoteProtoWrapper{} }
func (m *HasVoteProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*HasVoteProtoWrapper) ProtoMessage()    {}
func (*HasVoteProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *HasVoteProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasVoteProtoWrapper.Unmarshal(m, b)
}
func (m *HasVoteProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasVoteProtoWrapper.Marshal(b, m, deterministic)
}
func (m *HasVoteProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasVoteProtoWrapper.Merge(m, src)
}
func (m *HasVoteProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_HasVoteProtoWrapper.Size(m)
}
func (m *HasVoteProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_HasVoteProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_HasVoteProtoWrapper proto.InternalMessageInfo

func (m *HasVoteProtoWrapper) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HasVoteProtoWrapper) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *HasVoteProtoWrapper) GetType() types.SignedMsgType {
	if m != nil {
		return m.Type
	}
	return types.SignedMsgType_SIGNED_MSG_TYPE_UNKNOWN
}

func (m *HasVoteProtoWrapper) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// VoteSetBits is sent to communicate the bit-array of votes seen for the BlockID.
type VoteSetBitsProtoWrapper struct {
	Height               int64               `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32               `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Type                 types.SignedMsgType `protobuf:"varint,3,opt,name=type,proto3,enum=tendermint.types.SignedMsgType" json:"type,omitempty"`
	BlockId              *types.BlockIDProto `protobuf:"bytes,4,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Votes                *bits.BitArrayProto `protobuf:"bytes,5,opt,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VoteSetBitsProtoWrapper) Reset()         { *m = VoteSetBitsProtoWrapper{} }
func (m *VoteSetBitsProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*VoteSetBitsProtoWrapper) ProtoMessage()    {}
func (*VoteSetBitsProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *VoteSetBitsProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSetBitsProtoWrapper.Unmarshal(m, b)
}
func (m *VoteSetBitsProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSetBitsProtoWrapper.Marshal(b, m, deterministic)
}
func (m *VoteSetBitsProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSetBitsProtoWrapper.Merge(m, src)
}
func (m *VoteSetBitsProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_VoteSetBitsProtoWrapper.Size(m)
}
func (m *VoteSetBitsProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSetBitsProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSetBitsProtoWrapper proto.InternalMessageInfo

func (m *VoteSetBitsProtoWrapper) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VoteSetBitsProtoWrapper) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *VoteSetBitsProtoWrapper) GetType() types.SignedMsgType {
	if m != nil {
		return m.Type
	}
	return types.SignedMsgType_SIGNED_MSG_TYPE_UNKNOWN
}

func (m *VoteSetBitsProtoWrapper) GetBlockId() *types.BlockIDProto {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *VoteSetBitsProtoWrapper) GetVotes() *bits.BitArrayProto {
	if m != nil {
		return m.Votes
	}
	return nil
}

type BlockPartProtoWrapper struct {
	Height               int64            `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Round                int32            `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Part                 *types.PartProto `protobuf:"bytes,3,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockPartProtoWrapper) Reset()         { *m = BlockPartProtoWrapper{} }
func (m *BlockPartProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*BlockPartProtoWrapper) ProtoMessage()    {}
func (*BlockPartProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *BlockPartProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockPartProtoWrapper.Unmarshal(m, b)
}
func (m *BlockPartProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockPartProtoWrapper.Marshal(b, m, deterministic)
}
func (m *BlockPartProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockPartProtoWrapper.Merge(m, src)
}
func (m *BlockPartProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_BlockPartProtoWrapper.Size(m)
}
func (m *BlockPartProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockPartProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_BlockPartProtoWrapper proto.InternalMessageInfo

func (m *BlockPartProtoWrapper) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockPartProtoWrapper) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *BlockPartProtoWrapper) GetPart() *types.PartProto {
	if m != nil {
		return m.Part
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageProtoWrapper)(nil), "protobufs.consensusproto.MessageProtoWrapper")
	proto.RegisterType((*ProposalProtoWrapper)(nil), "protobufs.consensusproto.ProposalProtoWrapper")
	proto.RegisterType((*ProposalPOLProtoWrapper)(nil), "protobufs.consensusproto.ProposalPOLProtoWrapper")
	proto.RegisterType((*VoteProtoWrapper)(nil), "protobufs.consensusproto.VoteProtoWrapper")
	proto.RegisterType((*NewRoundStepProtoWrapper)(nil), "protobufs.consensusproto.NewRoundStepProtoWrapper")
	proto.RegisterType((*VoteSetMaj23ProtoWrapper)(nil), "protobufs.consensusproto.VoteSetMaj23ProtoWrapper")
	proto.RegisterType((*NewValidBlockProtoWrapper)(nil), "protobufs.consensusproto.NewValidBlockProtoWrapper")
	proto.RegisterType((*HasVoteProtoWrapper)(nil), "protobufs.consensusproto.HasVoteProtoWrapper")
	proto.RegisterType((*VoteSetBitsProtoWrapper)(nil), "protobufs.consensusproto.VoteSetBitsProtoWrapper")
	proto.RegisterType((*BlockPartProtoWrapper)(nil), "protobufs.consensusproto.BlockPartProtoWrapper")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xd1, 0x4e, 0xdb, 0x4a,
	0x10, 0x25, 0x90, 0x40, 0x98, 0x44, 0x5c, 0x64, 0xe0, 0xe2, 0x0b, 0x57, 0x17, 0x64, 0xee, 0x03,
	0xaa, 0x5a, 0x5b, 0x02, 0xf5, 0xb9, 0x60, 0x78, 0x08, 0x15, 0x50, 0xe4, 0x54, 0x54, 0x42, 0xaa,
	0xac, 0x75, 0x3c, 0x38, 0xdb, 0x3a, 0x5e, 0x6b, 0x77, 0x43, 0x88, 0xd4, 0x1f, 0xa8, 0x2a, 0xf5,
	0x4f, 0xfa, 0x03, 0xfd, 0x82, 0x7e, 0x05, 0x0f, 0xfd, 0x92, 0x6a, 0xd7, 0x26, 0xd8, 0x04, 0x2a,
	0x68, 0xa5, 0x3e, 0xd9, 0x3b, 0x3b, 0x73, 0x66, 0xce, 0x9c, 0xe3, 0x04, 0x1a, 0x72, 0x98, 0xa2,
	0xb0, 0x53, 0xce, 0x24, 0x33, 0x4c, 0xfd, 0x08, 0xfa, 0xe7, 0xc2, 0xee, 0xb0, 0x44, 0x60, 0x22,
	0xfa, 0x42, 0x87, 0x56, 0x16, 0x23, 0x16, 0x31, 0xfd, 0xea, 0xa8, 0xb7, 0x2c, 0x7f, 0xa5, 0x15,
	0x51, 0xd9, 0xed, 0x07, 0x76, 0x87, 0xf5, 0x9c, 0xee, 0x30, 0x45, 0x1e, 0x63, 0x18, 0x21, 0x77,
	0xce, 0x49, 0xc0, 0x69, 0xe7, 0x59, 0xc8, 0x59, 0x1a, 0xd3, 0xc0, 0xd1, 0xc9, 0xc2, 0x19, 0x81,
	0x3b, 0xba, 0xa7, 0x53, 0xe8, 0xbc, 0xe2, 0x3e, 0x0a, 0x29, 0xa6, 0x81, 0x70, 0x02, 0x2a, 0x4b,
	0x18, 0xd6, 0xd7, 0x0a, 0x2c, 0x1c, 0xa1, 0x10, 0x24, 0xc2, 0x13, 0x15, 0x78, 0xc3, 0x49, 0x9a,
	0x22, 0x37, 0x76, 0xa0, 0x7a, 0xc1, 0x24, 0x9a, 0xd3, 0xeb, 0x95, 0xcd, 0xc6, 0xd6, 0x13, 0xfb,
	0x3e, 0x92, 0xf6, 0x29, 0x93, 0xa5, 0xca, 0xd6, 0x84, 0xa7, 0x2b, 0x8d, 0x33, 0x98, 0x53, 0x4f,
	0x5f, 0xa0, 0xf4, 0x7b, 0xe4, 0xdd, 0xd6, 0xb6, 0x59, 0xd7, 0x58, 0x5b, 0x3f, 0xc7, 0x6a, 0xa3,
	0x3c, 0x52, 0xd9, 0xb7, 0x30, 0x9b, 0x17, 0x85, 0x3b, 0xb7, 0x06, 0x53, 0xa2, 0xdf, 0xb3, 0x06,
	0xb0, 0x78, 0xc2, 0x59, 0xca, 0x04, 0x89, 0x4b, 0xc3, 0xef, 0x42, 0x3d, 0xcd, 0xe3, 0x66, 0x45,
	0x37, 0x5d, 0xb3, 0x25, 0x26, 0x21, 0xf2, 0x1e, 0x4d, 0xa4, 0x9d, 0xf1, 0x2f, 0x55, 0xba, 0xd5,
	0x6f, 0x57, 0x6b, 0x13, 0xde, 0xa8, 0xcc, 0xf8, 0x17, 0x66, 0xf1, 0x52, 0x72, 0xb2, 0x4f, 0x24,
	0xd1, 0x83, 0x37, 0xbd, 0x9b, 0x80, 0xf5, 0xa5, 0x02, 0xcb, 0xa3, 0xfa, 0x57, 0x87, 0xa5, 0xe6,
	0x7f, 0xc3, 0x74, 0x17, 0x69, 0xd4, 0x95, 0xba, 0xf5, 0x94, 0x97, 0x9f, 0x8c, 0xa7, 0x60, 0x5c,
	0xa3, 0xfb, 0x29, 0x8b, 0x7d, 0xce, 0xfa, 0x49, 0x68, 0x4e, 0xae, 0x57, 0x36, 0x6b, 0xde, 0xfc,
	0xf5, 0xcd, 0x09, 0x8b, 0x3d, 0x15, 0x37, 0x0e, 0xa1, 0x59, 0xcc, 0x36, 0xa7, 0x34, 0x8d, 0x8d,
	0x22, 0x0d, 0x25, 0xa8, 0xad, 0x04, 0xb5, 0x5d, 0x2a, 0x77, 0x39, 0x27, 0xc3, 0x22, 0x95, 0x46,
	0x01, 0xd2, 0xda, 0x83, 0xf9, 0xdb, 0x3a, 0x19, 0x4e, 0xae, 0x70, 0xb6, 0xa0, 0xd5, 0xf1, 0x05,
	0x8d, 0x2a, 0x32, 0x41, 0x2d, 0x04, 0xf3, 0x18, 0x07, 0x7a, 0xbc, 0xb6, 0xc4, 0xb4, 0x04, 0x76,
	0x00, 0x73, 0x09, 0x0e, 0x32, 0x4e, 0xbe, 0x90, 0x98, 0xe6, 0xb0, 0x1b, 0xe3, 0xb0, 0x63, 0x18,
	0x5e, 0x33, 0x29, 0x84, 0x54, 0x9b, 0xfb, 0x7c, 0xa0, 0xda, 0xdc, 0xf2, 0xd4, 0xbd, 0x6d, 0xc6,
	0x30, 0xca, 0x16, 0xb2, 0x3e, 0x4d, 0xc2, 0x3f, 0xc7, 0x38, 0x38, 0x25, 0x31, 0x0d, 0xdd, 0x98,
	0x75, 0xde, 0x3f, 0x48, 0xc4, 0x45, 0xa8, 0x15, 0x75, 0xcb, 0x0e, 0xc6, 0x5b, 0x58, 0x0a, 0x14,
	0x84, 0x9f, 0x12, 0x2e, 0xf5, 0x70, 0x5d, 0x24, 0x21, 0xf2, 0x5c, 0xb5, 0xff, 0xef, 0x30, 0x1f,
	0xe1, 0xb2, 0x8d, 0xb2, 0xa5, 0xd3, 0x8a, 0xb2, 0x19, 0x1a, 0xa8, 0x74, 0x6d, 0xec, 0x43, 0xe3,
	0x06, 0x5e, 0x98, 0xd5, 0x07, 0x5b, 0xc1, 0x83, 0x11, 0x9a, 0x30, 0x56, 0x61, 0x96, 0x0a, 0xbf,
	0xc3, 0x7a, 0x3d, 0x2a, 0xcd, 0xda, 0x7a, 0x65, 0xb3, 0xee, 0xd5, 0xa9, 0xd8, 0xd3, 0x67, 0xeb,
	0x73, 0x05, 0x16, 0x5a, 0x44, 0x8c, 0x99, 0xe4, 0x71, 0x7b, 0xd8, 0x86, 0xaa, 0xa2, 0xa7, 0x69,
	0xcf, 0xdd, 0xf5, 0xcd, 0xb5, 0x69, 0x94, 0x60, 0x78, 0x24, 0xa2, 0xd7, 0xc3, 0x14, 0x3d, 0x9d,
	0xac, 0xa0, 0x68, 0x12, 0xe2, 0xa5, 0xe6, 0x55, 0xf3, 0xb2, 0x83, 0xf5, 0x71, 0x12, 0x96, 0x73,
	0x09, 0x5d, 0x2a, 0xc5, 0x9f, 0x1e, 0xea, 0x25, 0xd4, 0xb3, 0x95, 0xd3, 0x30, 0xdf, 0xf7, 0x7f,
	0xe3, 0x85, 0xda, 0x36, 0x07, 0xfb, 0x99, 0x7c, 0x7f, 0x29, 0xf9, 0xbe, 0x5f, 0xad, 0xcd, 0xe4,
	0x51, 0x6f, 0x46, 0x03, 0x1c, 0x84, 0xc6, 0x0b, 0xa8, 0x29, 0xe7, 0x09, 0xbd, 0xf4, 0x47, 0x7d,
	0xc3, 0x59, 0x9d, 0xf5, 0x01, 0x96, 0xdc, 0x6b, 0x1d, 0x7f, 0x63, 0x11, 0xcf, 0xa1, 0xaa, 0x0c,
	0x94, 0x9b, 0x72, 0xf5, 0x6e, 0x53, 0x16, 0xdb, 0xeb, 0x74, 0xd7, 0x3d, 0xdb, 0xf9, 0xc5, 0x7f,
	0xac, 0xd1, 0xaf, 0x7b, 0x30, 0xad, 0x83, 0xdb, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0xcb,
	0x44, 0x5f, 0x39, 0x07, 0x00, 0x00,
}
