// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package mock

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoC1ChannelMessageWrapper struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC1ChannelMessageWrapper) Reset()         { *m = DemoC1ChannelMessageWrapper{} }
func (m *DemoC1ChannelMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*DemoC1ChannelMessageWrapper) ProtoMessage()    {}
func (*DemoC1ChannelMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *DemoC1ChannelMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC1ChannelMessageWrapper.Unmarshal(m, b)
}
func (m *DemoC1ChannelMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC1ChannelMessageWrapper.Marshal(b, m, deterministic)
}
func (m *DemoC1ChannelMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC1ChannelMessageWrapper.Merge(m, src)
}
func (m *DemoC1ChannelMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_DemoC1ChannelMessageWrapper.Size(m)
}
func (m *DemoC1ChannelMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC1ChannelMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC1ChannelMessageWrapper proto.InternalMessageInfo

type DemoC1ChannelDataMessageWrapper struct {
	// Types that are valid to be assigned to Sum:
	//	*DemoC1ChannelDataMessageWrapper_DemoC1Message1
	//	*DemoC1ChannelDataMessageWrapper_DemoC1Message2
	Sum                  isDemoC1ChannelDataMessageWrapper_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DemoC1ChannelDataMessageWrapper) Reset()         { *m = DemoC1ChannelDataMessageWrapper{} }
func (m *DemoC1ChannelDataMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*DemoC1ChannelDataMessageWrapper) ProtoMessage()    {}
func (*DemoC1ChannelDataMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *DemoC1ChannelDataMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC1ChannelDataMessageWrapper.Unmarshal(m, b)
}
func (m *DemoC1ChannelDataMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC1ChannelDataMessageWrapper.Marshal(b, m, deterministic)
}
func (m *DemoC1ChannelDataMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC1ChannelDataMessageWrapper.Merge(m, src)
}
func (m *DemoC1ChannelDataMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_DemoC1ChannelDataMessageWrapper.Size(m)
}
func (m *DemoC1ChannelDataMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC1ChannelDataMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC1ChannelDataMessageWrapper proto.InternalMessageInfo

type isDemoC1ChannelDataMessageWrapper_Sum interface {
	isDemoC1ChannelDataMessageWrapper_Sum()
}

type DemoC1ChannelDataMessageWrapper_DemoC1Message1 struct {
	DemoC1Message1 *DemoC1Message1Proto `protobuf:"bytes,1,opt,name=demo_c1_message1,json=demoC1Message1,proto3,oneof"`
}

type DemoC1ChannelDataMessageWrapper_DemoC1Message2 struct {
	DemoC1Message2 *DemoC1Message2Proto `protobuf:"bytes,2,opt,name=demo_c1_message2,json=demoC1Message2,proto3,oneof"`
}

func (*DemoC1ChannelDataMessageWrapper_DemoC1Message1) isDemoC1ChannelDataMessageWrapper_Sum() {}

func (*DemoC1ChannelDataMessageWrapper_DemoC1Message2) isDemoC1ChannelDataMessageWrapper_Sum() {}

func (m *DemoC1ChannelDataMessageWrapper) GetSum() isDemoC1ChannelDataMessageWrapper_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *DemoC1ChannelDataMessageWrapper) GetDemoC1Message1() *DemoC1Message1Proto {
	if x, ok := m.GetSum().(*DemoC1ChannelDataMessageWrapper_DemoC1Message1); ok {
		return x.DemoC1Message1
	}
	return nil
}

func (m *DemoC1ChannelDataMessageWrapper) GetDemoC1Message2() *DemoC1Message2Proto {
	if x, ok := m.GetSum().(*DemoC1ChannelDataMessageWrapper_DemoC1Message2); ok {
		return x.DemoC1Message2
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DemoC1ChannelDataMessageWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DemoC1ChannelDataMessageWrapper_DemoC1Message1)(nil),
		(*DemoC1ChannelDataMessageWrapper_DemoC1Message2)(nil),
	}
}

type DemoC1Message1Proto struct {
	C11                  string   `protobuf:"bytes,1,opt,name=c11,proto3" json:"c11,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC1Message1Proto) Reset()         { *m = DemoC1Message1Proto{} }
func (m *DemoC1Message1Proto) String() string { return proto.CompactTextString(m) }
func (*DemoC1Message1Proto) ProtoMessage()    {}
func (*DemoC1Message1Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *DemoC1Message1Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC1Message1Proto.Unmarshal(m, b)
}
func (m *DemoC1Message1Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC1Message1Proto.Marshal(b, m, deterministic)
}
func (m *DemoC1Message1Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC1Message1Proto.Merge(m, src)
}
func (m *DemoC1Message1Proto) XXX_Size() int {
	return xxx_messageInfo_DemoC1Message1Proto.Size(m)
}
func (m *DemoC1Message1Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC1Message1Proto.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC1Message1Proto proto.InternalMessageInfo

func (m *DemoC1Message1Proto) GetC11() string {
	if m != nil {
		return m.C11
	}
	return ""
}

type DemoC1Message2Proto struct {
	C12                  string   `protobuf:"bytes,1,opt,name=c12,proto3" json:"c12,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC1Message2Proto) Reset()         { *m = DemoC1Message2Proto{} }
func (m *DemoC1Message2Proto) String() string { return proto.CompactTextString(m) }
func (*DemoC1Message2Proto) ProtoMessage()    {}
func (*DemoC1Message2Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *DemoC1Message2Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC1Message2Proto.Unmarshal(m, b)
}
func (m *DemoC1Message2Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC1Message2Proto.Marshal(b, m, deterministic)
}
func (m *DemoC1Message2Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC1Message2Proto.Merge(m, src)
}
func (m *DemoC1Message2Proto) XXX_Size() int {
	return xxx_messageInfo_DemoC1Message2Proto.Size(m)
}
func (m *DemoC1Message2Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC1Message2Proto.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC1Message2Proto proto.InternalMessageInfo

func (m *DemoC1Message2Proto) GetC12() string {
	if m != nil {
		return m.C12
	}
	return ""
}

type DemoC2ChannelMessageWrapper struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC2ChannelMessageWrapper) Reset()         { *m = DemoC2ChannelMessageWrapper{} }
func (m *DemoC2ChannelMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*DemoC2ChannelMessageWrapper) ProtoMessage()    {}
func (*DemoC2ChannelMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *DemoC2ChannelMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC2ChannelMessageWrapper.Unmarshal(m, b)
}
func (m *DemoC2ChannelMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC2ChannelMessageWrapper.Marshal(b, m, deterministic)
}
func (m *DemoC2ChannelMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC2ChannelMessageWrapper.Merge(m, src)
}
func (m *DemoC2ChannelMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_DemoC2ChannelMessageWrapper.Size(m)
}
func (m *DemoC2ChannelMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC2ChannelMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC2ChannelMessageWrapper proto.InternalMessageInfo

type DemoC2ChannelDataMessageWrapper struct {
	// Types that are valid to be assigned to Sum:
	//	*DemoC2ChannelDataMessageWrapper_DemoC2Message1
	//	*DemoC2ChannelDataMessageWrapper_DemoC2Message2
	Sum                  isDemoC2ChannelDataMessageWrapper_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *DemoC2ChannelDataMessageWrapper) Reset()         { *m = DemoC2ChannelDataMessageWrapper{} }
func (m *DemoC2ChannelDataMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*DemoC2ChannelDataMessageWrapper) ProtoMessage()    {}
func (*DemoC2ChannelDataMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{5}
}

func (m *DemoC2ChannelDataMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC2ChannelDataMessageWrapper.Unmarshal(m, b)
}
func (m *DemoC2ChannelDataMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC2ChannelDataMessageWrapper.Marshal(b, m, deterministic)
}
func (m *DemoC2ChannelDataMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC2ChannelDataMessageWrapper.Merge(m, src)
}
func (m *DemoC2ChannelDataMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_DemoC2ChannelDataMessageWrapper.Size(m)
}
func (m *DemoC2ChannelDataMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC2ChannelDataMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC2ChannelDataMessageWrapper proto.InternalMessageInfo

type isDemoC2ChannelDataMessageWrapper_Sum interface {
	isDemoC2ChannelDataMessageWrapper_Sum()
}

type DemoC2ChannelDataMessageWrapper_DemoC2Message1 struct {
	DemoC2Message1 *DemoC2Message1Proto `protobuf:"bytes,1,opt,name=demo_c2_message1,json=demoC2Message1,proto3,oneof"`
}

type DemoC2ChannelDataMessageWrapper_DemoC2Message2 struct {
	DemoC2Message2 *DemoC2Message2Proto `protobuf:"bytes,2,opt,name=demo_c2_message2,json=demoC2Message2,proto3,oneof"`
}

func (*DemoC2ChannelDataMessageWrapper_DemoC2Message1) isDemoC2ChannelDataMessageWrapper_Sum() {}

func (*DemoC2ChannelDataMessageWrapper_DemoC2Message2) isDemoC2ChannelDataMessageWrapper_Sum() {}

func (m *DemoC2ChannelDataMessageWrapper) GetSum() isDemoC2ChannelDataMessageWrapper_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *DemoC2ChannelDataMessageWrapper) GetDemoC2Message1() *DemoC2Message1Proto {
	if x, ok := m.GetSum().(*DemoC2ChannelDataMessageWrapper_DemoC2Message1); ok {
		return x.DemoC2Message1
	}
	return nil
}

func (m *DemoC2ChannelDataMessageWrapper) GetDemoC2Message2() *DemoC2Message2Proto {
	if x, ok := m.GetSum().(*DemoC2ChannelDataMessageWrapper_DemoC2Message2); ok {
		return x.DemoC2Message2
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DemoC2ChannelDataMessageWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DemoC2ChannelDataMessageWrapper_DemoC2Message1)(nil),
		(*DemoC2ChannelDataMessageWrapper_DemoC2Message2)(nil),
	}
}

type DemoC2Message1Proto struct {
	C21                  string   `protobuf:"bytes,1,opt,name=c21,proto3" json:"c21,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC2Message1Proto) Reset()         { *m = DemoC2Message1Proto{} }
func (m *DemoC2Message1Proto) String() string { return proto.CompactTextString(m) }
func (*DemoC2Message1Proto) ProtoMessage()    {}
func (*DemoC2Message1Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{6}
}

func (m *DemoC2Message1Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC2Message1Proto.Unmarshal(m, b)
}
func (m *DemoC2Message1Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC2Message1Proto.Marshal(b, m, deterministic)
}
func (m *DemoC2Message1Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC2Message1Proto.Merge(m, src)
}
func (m *DemoC2Message1Proto) XXX_Size() int {
	return xxx_messageInfo_DemoC2Message1Proto.Size(m)
}
func (m *DemoC2Message1Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC2Message1Proto.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC2Message1Proto proto.InternalMessageInfo

func (m *DemoC2Message1Proto) GetC21() string {
	if m != nil {
		return m.C21
	}
	return ""
}

type DemoC2Message2Proto struct {
	C22                  string   `protobuf:"bytes,1,opt,name=c22,proto3" json:"c22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoC2Message2Proto) Reset()         { *m = DemoC2Message2Proto{} }
func (m *DemoC2Message2Proto) String() string { return proto.CompactTextString(m) }
func (*DemoC2Message2Proto) ProtoMessage()    {}
func (*DemoC2Message2Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{7}
}

func (m *DemoC2Message2Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoC2Message2Proto.Unmarshal(m, b)
}
func (m *DemoC2Message2Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoC2Message2Proto.Marshal(b, m, deterministic)
}
func (m *DemoC2Message2Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoC2Message2Proto.Merge(m, src)
}
func (m *DemoC2Message2Proto) XXX_Size() int {
	return xxx_messageInfo_DemoC2Message2Proto.Size(m)
}
func (m *DemoC2Message2Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoC2Message2Proto.DiscardUnknown(m)
}

var xxx_messageInfo_DemoC2Message2Proto proto.InternalMessageInfo

func (m *DemoC2Message2Proto) GetC22() string {
	if m != nil {
		return m.C22
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoC1ChannelMessageWrapper)(nil), "protocols.p2p.DemoC1ChannelMessageWrapper")
	proto.RegisterType((*DemoC1ChannelDataMessageWrapper)(nil), "protocols.p2p.DemoC1ChannelDataMessageWrapper")
	proto.RegisterType((*DemoC1Message1Proto)(nil), "protocols.p2p.DemoC1Message1Proto")
	proto.RegisterType((*DemoC1Message2Proto)(nil), "protocols.p2p.DemoC1Message2Proto")
	proto.RegisterType((*DemoC2ChannelMessageWrapper)(nil), "protocols.p2p.DemoC2ChannelMessageWrapper")
	proto.RegisterType((*DemoC2ChannelDataMessageWrapper)(nil), "protocols.p2p.DemoC2ChannelDataMessageWrapper")
	proto.RegisterType((*DemoC2Message1Proto)(nil), "protocols.p2p.DemoC2Message1Proto")
	proto.RegisterType((*DemoC2Message2Proto)(nil), "protocols.p2p.DemoC2Message2Proto")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd0, 0x4f, 0x4b, 0x84, 0x40,
	0x18, 0x06, 0xf0, 0x6c, 0x29, 0x68, 0xa2, 0x58, 0xec, 0xb2, 0x10, 0x51, 0x78, 0xa9, 0x4b, 0xca,
	0x3c, 0xdd, 0xa2, 0xd3, 0xee, 0x1e, 0xba, 0x14, 0xb1, 0x97, 0xa0, 0xcb, 0x32, 0x8e, 0x6f, 0x2a,
	0x39, 0xce, 0x30, 0xba, 0x87, 0xbe, 0x61, 0x1f, 0x2b, 0xd4, 0xc8, 0x15, 0x5d, 0xd6, 0x93, 0x7f,
	0xde, 0x67, 0x9e, 0x79, 0xf9, 0x31, 0x16, 0x91, 0xd2, 0xbe, 0xb1, 0xba, 0xd4, 0xee, 0x59, 0xfd,
	0x90, 0x3a, 0x2b, 0x7c, 0x03, 0xe3, 0x5d, 0xb1, 0xcb, 0x25, 0x29, 0xbd, 0xe0, 0x8b, 0x44, 0xe4,
	0x39, 0x65, 0x2f, 0x54, 0x14, 0x22, 0xa6, 0x77, 0x2b, 0x8c, 0x21, 0xeb, 0xfd, 0x38, 0xec, 0xba,
	0x33, 0x5f, 0x8a, 0x52, 0x74, 0x33, 0xee, 0x2b, 0x9b, 0x56, 0xfd, 0x6b, 0xc9, 0xd7, 0xaa, 0x99,
	0xf0, 0x99, 0x73, 0xe3, 0xdc, 0x9d, 0xc2, 0xf3, 0x3b, 0x97, 0xf9, 0x4d, 0xd3, 0xdf, 0x71, 0xfe,
	0x56, 0xcd, 0x9e, 0x0f, 0x56, 0xe7, 0x51, 0xe7, 0xf7, 0x40, 0x1f, 0x66, 0x87, 0xfb, 0xfb, 0x30,
	0xdc, 0x87, 0xf9, 0x11, 0x9b, 0x14, 0x1b, 0xe5, 0xdd, 0xb2, 0x8b, 0x81, 0xfb, 0xdd, 0x29, 0x9b,
	0x48, 0xde, 0x2c, 0x7c, 0xb2, 0xaa, 0x5e, 0x7b, 0x41, 0x6c, 0x05, 0xd1, 0x06, 0xf1, 0x6f, 0x87,
	0x3d, 0x76, 0x18, 0x61, 0x87, 0x51, 0x76, 0x18, 0xb6, 0x43, 0xdf, 0x0e, 0xa3, 0xec, 0x30, 0x6c,
	0x87, 0x5d, 0x76, 0xe8, 0xdb, 0xa1, 0xb5, 0x03, 0xef, 0x05, 0xb7, 0xec, 0xd0, 0xda, 0x01, 0xf3,
	0xa7, 0x8f, 0xc7, 0x38, 0x2d, 0x93, 0x4d, 0xe8, 0x4b, 0xad, 0x82, 0xe4, 0xdb, 0x90, 0xcd, 0x28,
	0x8a, 0xc9, 0x06, 0x9f, 0x22, 0xb4, 0xa9, 0xbc, 0x8f, 0xac, 0x36, 0x59, 0x1a, 0x06, 0x25, 0x59,
	0x95, 0xe6, 0x22, 0x0b, 0xea, 0xf5, 0x8b, 0x40, 0x69, 0xf9, 0x15, 0x1e, 0xd7, 0x1f, 0x0f, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x63, 0x99, 0x19, 0xd9, 0x02, 0x00, 0x00,
}
