// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TendermintExtraDataProtoWrapper struct {
	// 包含commit的信息,上一个区块的commit
	LastCommit *CommitProto `protobuf:"bytes,1,opt,name=lastCommit,proto3" json:"lastCommit,omitempty"`
	// 以及区块的evidence
	Evidence *EvidenceListProto     `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	ChainId  string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Time     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	// prev block info
	LastBlockId *BlockIDProto `protobuf:"bytes,5,opt,name=last_block_id,json=lastBlockId,proto3" json:"last_block_id,omitempty"`
	// hashes of block data
	LastCommitHash []byte `protobuf:"bytes,6,opt,name=last_commit_hash,json=lastCommitHash,proto3" json:"last_commit_hash,omitempty"`
	// hashes from the app output from the prev block
	ValidatorsHash     []byte `protobuf:"bytes,7,opt,name=validators_hash,json=validatorsHash,proto3" json:"validators_hash,omitempty"`
	NextValidatorsHash []byte `protobuf:"bytes,8,opt,name=next_validators_hash,json=nextValidatorsHash,proto3" json:"next_validators_hash,omitempty"`
	ConsensusHash      []byte `protobuf:"bytes,9,opt,name=consensus_hash,json=consensusHash,proto3" json:"consensus_hash,omitempty"`
	LastResultsHash    []byte `protobuf:"bytes,10,opt,name=last_results_hash,json=lastResultsHash,proto3" json:"last_results_hash,omitempty"`
	// consensus info
	EvidenceHash         []byte   `protobuf:"bytes,11,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	ProposerAddress      []byte   `protobuf:"bytes,12,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TendermintExtraDataProtoWrapper) Reset()         { *m = TendermintExtraDataProtoWrapper{} }
func (m *TendermintExtraDataProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*TendermintExtraDataProtoWrapper) ProtoMessage()    {}
func (*TendermintExtraDataProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *TendermintExtraDataProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintExtraDataProtoWrapper.Unmarshal(m, b)
}
func (m *TendermintExtraDataProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintExtraDataProtoWrapper.Marshal(b, m, deterministic)
}
func (m *TendermintExtraDataProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintExtraDataProtoWrapper.Merge(m, src)
}
func (m *TendermintExtraDataProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_TendermintExtraDataProtoWrapper.Size(m)
}
func (m *TendermintExtraDataProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintExtraDataProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintExtraDataProtoWrapper proto.InternalMessageInfo

func (m *TendermintExtraDataProtoWrapper) GetLastCommit() *CommitProto {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetEvidence() *EvidenceListProto {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *TendermintExtraDataProtoWrapper) GetTime() *timestamppb.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetLastBlockId() *BlockIDProto {
	if m != nil {
		return m.LastBlockId
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetLastCommitHash() []byte {
	if m != nil {
		return m.LastCommitHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetValidatorsHash() []byte {
	if m != nil {
		return m.ValidatorsHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetNextValidatorsHash() []byte {
	if m != nil {
		return m.NextValidatorsHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetConsensusHash() []byte {
	if m != nil {
		return m.ConsensusHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetLastResultsHash() []byte {
	if m != nil {
		return m.LastResultsHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetEvidenceHash() []byte {
	if m != nil {
		return m.EvidenceHash
	}
	return nil
}

func (m *TendermintExtraDataProtoWrapper) GetProposerAddress() []byte {
	if m != nil {
		return m.ProposerAddress
	}
	return nil
}

// fabric block 中的extra data的反序列化struct
type TendermintBlockProtoWrapper struct {
	// fabric 的block 信息
	Header *TendermintBlockHeaderProto `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *TendermintBlockDataProto   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// fabric的元数据
	//  common.BlockMetadata blockMetadata = 3;
	BlockMetadata [][]byte `protobuf:"bytes,3,rep,name=blockMetadata,proto3" json:"blockMetadata,omitempty"`
	// 包含commit的信息,上一个区块的commit
	LastCommit *CommitProto `protobuf:"bytes,4,opt,name=lastCommit,proto3" json:"lastCommit,omitempty"`
	// 以及区块的evidence
	Evidence             *EvidenceListProto `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TendermintBlockProtoWrapper) Reset()         { *m = TendermintBlockProtoWrapper{} }
func (m *TendermintBlockProtoWrapper) String() string { return proto.CompactTextString(m) }
func (*TendermintBlockProtoWrapper) ProtoMessage()    {}
func (*TendermintBlockProtoWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *TendermintBlockProtoWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintBlockProtoWrapper.Unmarshal(m, b)
}
func (m *TendermintBlockProtoWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintBlockProtoWrapper.Marshal(b, m, deterministic)
}
func (m *TendermintBlockProtoWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintBlockProtoWrapper.Merge(m, src)
}
func (m *TendermintBlockProtoWrapper) XXX_Size() int {
	return xxx_messageInfo_TendermintBlockProtoWrapper.Size(m)
}
func (m *TendermintBlockProtoWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintBlockProtoWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintBlockProtoWrapper proto.InternalMessageInfo

func (m *TendermintBlockProtoWrapper) GetHeader() *TendermintBlockHeaderProto {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TendermintBlockProtoWrapper) GetData() *TendermintBlockDataProto {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TendermintBlockProtoWrapper) GetBlockMetadata() [][]byte {
	if m != nil {
		return m.BlockMetadata
	}
	return nil
}

func (m *TendermintBlockProtoWrapper) GetLastCommit() *CommitProto {
	if m != nil {
		return m.LastCommit
	}
	return nil
}

func (m *TendermintBlockProtoWrapper) GetEvidence() *EvidenceListProto {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func init() {
	proto.RegisterType((*TendermintExtraDataProtoWrapper)(nil), "tendermint.types.TendermintExtraDataProtoWrapper")
	proto.RegisterType((*TendermintBlockProtoWrapper)(nil), "tendermint.types.TendermintBlockProtoWrapper")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xe9, 0x9a, 0xb5, 0x9d, 0xdb, 0x6e, 0x25, 0xda, 0x45, 0x54, 0x04, 0xad, 0x36, 0xfe,
	0x94, 0x09, 0x12, 0x04, 0x37, 0x5c, 0xc0, 0x24, 0xba, 0x56, 0x6a, 0x05, 0x48, 0x28, 0x9a, 0x40,
	0xe2, 0xa6, 0x72, 0x62, 0x2f, 0xb1, 0x48, 0xe2, 0xc8, 0x76, 0xa7, 0xed, 0x2d, 0x78, 0x2c, 0xee,
	0x78, 0x83, 0x21, 0xf1, 0x1a, 0xdc, 0x20, 0x1f, 0x27, 0xed, 0xda, 0x5e, 0x20, 0xd1, 0x9b, 0xb6,
	0xfa, 0xce, 0xef, 0xfb, 0x72, 0x72, 0x7c, 0x5c, 0xd4, 0x0c, 0x12, 0x1e, 0x7e, 0x73, 0x73, 0xc1,
	0x15, 0xb7, 0x3b, 0x8a, 0x66, 0x84, 0x8a, 0x94, 0x65, 0xca, 0x55, 0xd7, 0x39, 0x95, 0xdd, 0xc3,
	0x88, 0x47, 0x1c, 0x8a, 0x9e, 0xfe, 0x65, 0xb8, 0xee, 0x24, 0x62, 0x2a, 0x9e, 0x07, 0x6e, 0xc8,
	0x53, 0x2f, 0xbe, 0xce, 0xa9, 0x48, 0x28, 0x89, 0xa8, 0xf0, 0x2e, 0x70, 0x20, 0x58, 0xf8, 0x9c,
	0x08, 0x9e, 0x27, 0x2c, 0xf0, 0x00, 0x96, 0xe6, 0x2b, 0x98, 0x5f, 0x48, 0x0f, 0x32, 0xcd, 0x67,
	0x91, 0xf4, 0x7e, 0xab, 0x24, 0x7a, 0xc9, 0x08, 0xcd, 0x42, 0x5a, 0x84, 0xf5, 0x22, 0xce, 0xa3,
	0x84, 0x2e, 0x30, 0x4f, 0xb1, 0x94, 0x4a, 0x85, 0xd3, 0xdc, 0x00, 0x47, 0x7f, 0x2c, 0xd4, 0x3b,
	0x5f, 0xbc, 0xe2, 0xf8, 0x4a, 0x09, 0x3c, 0xc2, 0x0a, 0x7f, 0xd2, 0xc5, 0x2f, 0x02, 0xe7, 0x39,
	0x15, 0xf6, 0x5b, 0x84, 0x12, 0x2c, 0xd5, 0x19, 0x4f, 0x53, 0xa6, 0x9c, 0x4a, 0xbf, 0x32, 0x68,
	0xbe, 0xbc, 0xef, 0xae, 0x0f, 0xc6, 0x35, 0x75, 0x70, 0xfa, 0xb7, 0x0c, 0xf6, 0x18, 0x35, 0xca,
	0xae, 0x9c, 0x1d, 0x30, 0x1f, 0x6f, 0x9a, 0xc7, 0x05, 0xf1, 0x81, 0x49, 0x13, 0x31, 0xb4, 0x7e,
	0xdc, 0xf4, 0xee, 0xf8, 0x0b, 0xab, 0xfd, 0x18, 0x35, 0xc2, 0x18, 0xb3, 0x6c, 0xc6, 0x88, 0x53,
	0xed, 0x57, 0x06, 0x7b, 0xc3, 0xe6, 0xef, 0x9b, 0x5e, 0xfd, 0x4c, 0x6b, 0xd3, 0x91, 0x5f, 0x87,
	0xe2, 0x94, 0xd8, 0xaf, 0x91, 0xa5, 0x5f, 0xd2, 0xb1, 0xe0, 0x51, 0x5d, 0xd7, 0x4c, 0xc0, 0x2d,
	0x27, 0xe0, 0x9e, 0x97, 0x13, 0x18, 0x36, 0xf4, 0x13, 0xbe, 0xff, 0xea, 0x55, 0x7c, 0x70, 0xd8,
	0x13, 0xd4, 0xd6, 0x6d, 0xcf, 0xe0, 0xfc, 0xf5, 0x63, 0x76, 0x21, 0xe2, 0xc1, 0x66, 0xb7, 0x43,
	0x4d, 0x4c, 0x47, 0xb7, 0x1b, 0x6d, 0x6a, 0xab, 0xd1, 0x89, 0x3d, 0x40, 0x1d, 0x48, 0x0a, 0x61,
	0x02, 0xb3, 0x18, 0xcb, 0xd8, 0xa9, 0xf5, 0x2b, 0x83, 0x96, 0xbf, 0xbf, 0x1c, 0xcc, 0x04, 0xcb,
	0xd8, 0x7e, 0x82, 0x0e, 0x2e, 0x71, 0xc2, 0x08, 0x56, 0x5c, 0x48, 0x03, 0xd6, 0x0d, 0xb8, 0x94,
	0x01, 0x7c, 0x81, 0x0e, 0x33, 0x7a, 0xa5, 0x66, 0xeb, 0x74, 0x03, 0x68, 0x5b, 0xd7, 0x3e, 0xaf,
	0x3a, 0x1e, 0xa1, 0xfd, 0x90, 0x67, 0x92, 0x66, 0x72, 0x5e, 0xb0, 0x7b, 0xc0, 0xb6, 0x17, 0x2a,
	0x60, 0x27, 0xe8, 0x2e, 0xf4, 0x2a, 0xa8, 0x9c, 0x27, 0xaa, 0x20, 0x11, 0x90, 0x07, 0xba, 0xe0,
	0x1b, 0x1d, 0xd8, 0x63, 0xd4, 0x2e, 0xcf, 0xc3, 0x70, 0x4d, 0xe0, 0x5a, 0xa5, 0x08, 0xd0, 0x53,
	0xd4, 0xc9, 0x05, 0xcf, 0xb9, 0xa4, 0x62, 0x86, 0x09, 0x11, 0x54, 0x4a, 0xa7, 0x65, 0xf2, 0x4a,
	0xfd, 0x9d, 0x91, 0x8f, 0x7e, 0xee, 0xa0, 0x7b, 0xcb, 0xed, 0x83, 0xe9, 0xad, 0x6c, 0xde, 0x08,
	0xd5, 0x62, 0x8a, 0x09, 0x15, 0xc5, 0xd6, 0x3d, 0xdb, 0x3c, 0x8a, 0x35, 0xfb, 0x04, 0x70, 0xb3,
	0x84, 0x85, 0xd7, 0x3e, 0x45, 0x16, 0xc1, 0x0a, 0x17, 0xcb, 0x77, 0xf2, 0xcf, 0x8c, 0xc5, 0x05,
	0xf0, 0xc1, 0x67, 0x3f, 0x44, 0x6d, 0x58, 0x89, 0x8f, 0x54, 0x61, 0x08, 0xaa, 0xf6, 0xab, 0x7a,
	0x8e, 0x2b, 0xe2, 0xda, 0x2d, 0xb1, 0xb6, 0xb9, 0x25, 0xbb, 0xff, 0x7d, 0x4b, 0x86, 0xa7, 0x5f,
	0xdf, 0x6c, 0xf3, 0xff, 0x11, 0xd4, 0x40, 0x78, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x12,
	0xe1, 0x82, 0x05, 0x05, 0x00, 0x00,
}
