// Code generated by protoc-gen-go. DO NOT EDIT.
// source: evidence.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EvidenceProto struct {
	// Types that are valid to be assigned to Sum:
	//	*EvidenceProto_DuplicateVoteEvidence
	//	*EvidenceProto_LightClientAttackEvidence
	Sum                  isEvidenceProto_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EvidenceProto) Reset()         { *m = EvidenceProto{} }
func (m *EvidenceProto) String() string { return proto.CompactTextString(m) }
func (*EvidenceProto) ProtoMessage()    {}
func (*EvidenceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b1d6725573e3e5a, []int{0}
}

func (m *EvidenceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceProto.Unmarshal(m, b)
}
func (m *EvidenceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceProto.Marshal(b, m, deterministic)
}
func (m *EvidenceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceProto.Merge(m, src)
}
func (m *EvidenceProto) XXX_Size() int {
	return xxx_messageInfo_EvidenceProto.Size(m)
}
func (m *EvidenceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceProto.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceProto proto.InternalMessageInfo

type isEvidenceProto_Sum interface {
	isEvidenceProto_Sum()
}

type EvidenceProto_DuplicateVoteEvidence struct {
	DuplicateVoteEvidence *DuplicateVoteEvidenceProto `protobuf:"bytes,1,opt,name=duplicate_vote_evidence,json=duplicateVoteEvidence,proto3,oneof"`
}

type EvidenceProto_LightClientAttackEvidence struct {
	LightClientAttackEvidence *LightClientAttackEvidenceProto `protobuf:"bytes,2,opt,name=light_client_attack_evidence,json=lightClientAttackEvidence,proto3,oneof"`
}

func (*EvidenceProto_DuplicateVoteEvidence) isEvidenceProto_Sum() {}

func (*EvidenceProto_LightClientAttackEvidence) isEvidenceProto_Sum() {}

func (m *EvidenceProto) GetSum() isEvidenceProto_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *EvidenceProto) GetDuplicateVoteEvidence() *DuplicateVoteEvidenceProto {
	if x, ok := m.GetSum().(*EvidenceProto_DuplicateVoteEvidence); ok {
		return x.DuplicateVoteEvidence
	}
	return nil
}

func (m *EvidenceProto) GetLightClientAttackEvidence() *LightClientAttackEvidenceProto {
	if x, ok := m.GetSum().(*EvidenceProto_LightClientAttackEvidence); ok {
		return x.LightClientAttackEvidence
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EvidenceProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EvidenceProto_DuplicateVoteEvidence)(nil),
		(*EvidenceProto_LightClientAttackEvidence)(nil),
	}
}

// DuplicateVoteEvidence contains evidence of a validator signed two conflicting votes.
type DuplicateVoteEvidenceProto struct {
	VoteA                *VoteProto             `protobuf:"bytes,1,opt,name=vote_a,json=voteA,proto3" json:"vote_a,omitempty"`
	VoteB                *VoteProto             `protobuf:"bytes,2,opt,name=vote_b,json=voteB,proto3" json:"vote_b,omitempty"`
	TotalVotingPower     int64                  `protobuf:"varint,3,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	ValidatorPower       int64                  `protobuf:"varint,4,opt,name=validator_power,json=validatorPower,proto3" json:"validator_power,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DuplicateVoteEvidenceProto) Reset()         { *m = DuplicateVoteEvidenceProto{} }
func (m *DuplicateVoteEvidenceProto) String() string { return proto.CompactTextString(m) }
func (*DuplicateVoteEvidenceProto) ProtoMessage()    {}
func (*DuplicateVoteEvidenceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b1d6725573e3e5a, []int{1}
}

func (m *DuplicateVoteEvidenceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateVoteEvidenceProto.Unmarshal(m, b)
}
func (m *DuplicateVoteEvidenceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateVoteEvidenceProto.Marshal(b, m, deterministic)
}
func (m *DuplicateVoteEvidenceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateVoteEvidenceProto.Merge(m, src)
}
func (m *DuplicateVoteEvidenceProto) XXX_Size() int {
	return xxx_messageInfo_DuplicateVoteEvidenceProto.Size(m)
}
func (m *DuplicateVoteEvidenceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateVoteEvidenceProto.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateVoteEvidenceProto proto.InternalMessageInfo

func (m *DuplicateVoteEvidenceProto) GetVoteA() *VoteProto {
	if m != nil {
		return m.VoteA
	}
	return nil
}

func (m *DuplicateVoteEvidenceProto) GetVoteB() *VoteProto {
	if m != nil {
		return m.VoteB
	}
	return nil
}

func (m *DuplicateVoteEvidenceProto) GetTotalVotingPower() int64 {
	if m != nil {
		return m.TotalVotingPower
	}
	return 0
}

func (m *DuplicateVoteEvidenceProto) GetValidatorPower() int64 {
	if m != nil {
		return m.ValidatorPower
	}
	return 0
}

func (m *DuplicateVoteEvidenceProto) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

// LightClientAttackEvidence contains evidence of a set of validators attempting to mislead a light client.
type LightClientAttackEvidenceProto struct {
	ConflictingBlock     *LightBlockProto       `protobuf:"bytes,1,opt,name=conflicting_block,json=conflictingBlock,proto3" json:"conflicting_block,omitempty"`
	CommonHeight         int64                  `protobuf:"varint,2,opt,name=common_height,json=commonHeight,proto3" json:"common_height,omitempty"`
	ByzantineValidators  []*ValidatorProto      `protobuf:"bytes,3,rep,name=byzantine_validators,json=byzantineValidators,proto3" json:"byzantine_validators,omitempty"`
	TotalVotingPower     int64                  `protobuf:"varint,4,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LightClientAttackEvidenceProto) Reset()         { *m = LightClientAttackEvidenceProto{} }
func (m *LightClientAttackEvidenceProto) String() string { return proto.CompactTextString(m) }
func (*LightClientAttackEvidenceProto) ProtoMessage()    {}
func (*LightClientAttackEvidenceProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b1d6725573e3e5a, []int{2}
}

func (m *LightClientAttackEvidenceProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LightClientAttackEvidenceProto.Unmarshal(m, b)
}
func (m *LightClientAttackEvidenceProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LightClientAttackEvidenceProto.Marshal(b, m, deterministic)
}
func (m *LightClientAttackEvidenceProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LightClientAttackEvidenceProto.Merge(m, src)
}
func (m *LightClientAttackEvidenceProto) XXX_Size() int {
	return xxx_messageInfo_LightClientAttackEvidenceProto.Size(m)
}
func (m *LightClientAttackEvidenceProto) XXX_DiscardUnknown() {
	xxx_messageInfo_LightClientAttackEvidenceProto.DiscardUnknown(m)
}

var xxx_messageInfo_LightClientAttackEvidenceProto proto.InternalMessageInfo

func (m *LightClientAttackEvidenceProto) GetConflictingBlock() *LightBlockProto {
	if m != nil {
		return m.ConflictingBlock
	}
	return nil
}

func (m *LightClientAttackEvidenceProto) GetCommonHeight() int64 {
	if m != nil {
		return m.CommonHeight
	}
	return 0
}

func (m *LightClientAttackEvidenceProto) GetByzantineValidators() []*ValidatorProto {
	if m != nil {
		return m.ByzantineValidators
	}
	return nil
}

func (m *LightClientAttackEvidenceProto) GetTotalVotingPower() int64 {
	if m != nil {
		return m.TotalVotingPower
	}
	return 0
}

func (m *LightClientAttackEvidenceProto) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type EvidenceListProto struct {
	Evidence             []*EvidenceProto `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EvidenceListProto) Reset()         { *m = EvidenceListProto{} }
func (m *EvidenceListProto) String() string { return proto.CompactTextString(m) }
func (*EvidenceListProto) ProtoMessage()    {}
func (*EvidenceListProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b1d6725573e3e5a, []int{3}
}

func (m *EvidenceListProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceListProto.Unmarshal(m, b)
}
func (m *EvidenceListProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceListProto.Marshal(b, m, deterministic)
}
func (m *EvidenceListProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceListProto.Merge(m, src)
}
func (m *EvidenceListProto) XXX_Size() int {
	return xxx_messageInfo_EvidenceListProto.Size(m)
}
func (m *EvidenceListProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceListProto.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceListProto proto.InternalMessageInfo

func (m *EvidenceListProto) GetEvidence() []*EvidenceProto {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func init() {
	proto.RegisterType((*EvidenceProto)(nil), "tendermint.types.EvidenceProto")
	proto.RegisterType((*DuplicateVoteEvidenceProto)(nil), "tendermint.types.DuplicateVoteEvidenceProto")
	proto.RegisterType((*LightClientAttackEvidenceProto)(nil), "tendermint.types.LightClientAttackEvidenceProto")
	proto.RegisterType((*EvidenceListProto)(nil), "tendermint.types.EvidenceListProto")
}

func init() { proto.RegisterFile("evidence.proto", fileDescriptor_9b1d6725573e3e5a) }

var fileDescriptor_9b1d6725573e3e5a = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0xe2, 0xa4, 0x2a, 0x5b, 0x5a, 0x52, 0x53, 0x44, 0x08, 0x88, 0x84, 0x70, 0x20, 0x87,
	0x62, 0xa3, 0x70, 0x45, 0x48, 0x31, 0x20, 0xe5, 0x10, 0xa1, 0xca, 0xa0, 0x1c, 0xb8, 0x58, 0xeb,
	0xf5, 0xc6, 0x59, 0x75, 0xed, 0xb5, 0xec, 0x49, 0x50, 0x78, 0x0a, 0xde, 0x80, 0xd7, 0xe1, 0x21,
	0x10, 0x3c, 0x04, 0x2f, 0x80, 0x76, 0xec, 0x6c, 0x7f, 0xd2, 0xc0, 0xa1, 0x5c, 0xa2, 0x78, 0xe6,
	0xfb, 0x66, 0xe6, 0xfb, 0x66, 0x6c, 0x72, 0xc8, 0x97, 0x22, 0xe2, 0x29, 0xe3, 0x4e, 0x96, 0x2b,
	0x50, 0x76, 0x0b, 0x78, 0x1a, 0xf1, 0x3c, 0x11, 0x29, 0x38, 0xb0, 0xca, 0x78, 0xd1, 0x39, 0x8e,
	0x55, 0xac, 0x30, 0xe9, 0xea, 0x7f, 0x25, 0xae, 0xd3, 0x8d, 0x95, 0x8a, 0x25, 0x77, 0xf1, 0x29,
	0x5c, 0xcc, 0x5c, 0x10, 0x09, 0x2f, 0x80, 0x26, 0x59, 0x05, 0x18, 0xc7, 0x02, 0xe6, 0x8b, 0xd0,
	0x61, 0x2a, 0x71, 0xe7, 0xab, 0x8c, 0xe7, 0x92, 0x47, 0x31, 0xcf, 0xdd, 0x19, 0x0d, 0x73, 0xc1,
	0x9e, 0x47, 0xb9, 0xca, 0xa4, 0x08, 0x4b, 0x7e, 0x61, 0xca, 0x14, 0x2e, 0x36, 0x2d, 0x7f, 0xab,
	0x4a, 0x93, 0x1b, 0x55, 0x5a, 0x52, 0x29, 0x22, 0x0a, 0x2a, 0x2f, 0xab, 0xf5, 0x7f, 0xd7, 0xc8,
	0xc1, 0xbb, 0x4a, 0xf3, 0x29, 0x4a, 0x9e, 0x91, 0xfb, 0xd1, 0x22, 0x93, 0x82, 0x51, 0xe0, 0xc1,
	0x52, 0x01, 0x0f, 0xd6, 0x9e, 0xb4, 0x6b, 0xbd, 0xda, 0x60, 0x7f, 0x78, 0xe2, 0x5c, 0x35, 0xc5,
	0x79, 0xbb, 0x26, 0x4c, 0x15, 0xf0, 0x4b, 0xe5, 0xc6, 0x3b, 0xfe, 0xbd, 0xe8, 0xba, 0xac, 0x5d,
	0x90, 0x47, 0x52, 0xc4, 0x73, 0x08, 0x98, 0x14, 0x3c, 0x85, 0x80, 0x02, 0x50, 0x76, 0x76, 0xde,
	0xac, 0x8e, 0xcd, 0x5e, 0x6c, 0x36, 0x9b, 0x68, 0xd6, 0x1b, 0x24, 0x8d, 0x90, 0x73, 0xb5, 0xe1,
	0x03, 0xb9, 0x0d, 0xe1, 0x35, 0x89, 0x55, 0x2c, 0x92, 0xfe, 0xb7, 0x3a, 0xe9, 0x6c, 0x9f, 0xd9,
	0x1e, 0x92, 0x5d, 0x14, 0x4e, 0x2b, 0xc5, 0x0f, 0x37, 0x87, 0xd0, 0x24, 0x04, 0xfb, 0x4d, 0x0d,
	0x1d, 0x19, 0x4e, 0x58, 0x0d, 0xfe, 0x6f, 0x8e, 0x67, 0x9f, 0x10, 0x1b, 0x14, 0x50, 0xa9, 0x6d,
	0x16, 0x69, 0x1c, 0x64, 0xea, 0x33, 0xcf, 0xdb, 0x56, 0xaf, 0x36, 0xb0, 0xfc, 0x16, 0x66, 0xa6,
	0x98, 0x38, 0xd5, 0x71, 0xfb, 0x19, 0xb9, 0x63, 0xb6, 0x57, 0x41, 0x1b, 0x08, 0x3d, 0x34, 0xe1,
	0x12, 0xe8, 0x91, 0x5b, 0xe6, 0xfc, 0xda, 0x4d, 0x9c, 0xa6, 0xe3, 0x94, 0x07, 0xea, 0xac, 0xef,
	0xc1, 0xf9, 0xb8, 0x46, 0x78, 0x7b, 0xdf, 0x7f, 0x76, 0x77, 0xbe, 0xfe, 0xea, 0xd6, 0xfc, 0x73,
	0x5a, 0xff, 0x47, 0x9d, 0x3c, 0xfe, 0xbb, 0xd1, 0xf6, 0x7b, 0x72, 0xc4, 0x54, 0x3a, 0x93, 0x82,
	0xe1, 0xf0, 0xa1, 0x54, 0xec, 0xac, 0x32, 0xec, 0xc9, 0x96, 0xad, 0x79, 0x1a, 0x53, 0x5a, 0xd0,
	0xba, 0xc0, 0xc5, 0xb0, 0xfd, 0x94, 0x1c, 0x30, 0x95, 0x24, 0x2a, 0x0d, 0xe6, 0x5c, 0x83, 0xd1,
	0x48, 0xcb, 0xbf, 0x5d, 0x06, 0xc7, 0x18, 0xb3, 0x3f, 0x90, 0xe3, 0x70, 0xf5, 0x85, 0xa6, 0x20,
	0x52, 0x1e, 0x18, 0xdd, 0x45, 0xdb, 0xea, 0x59, 0x83, 0xfd, 0x61, 0xef, 0x1a, 0xd3, 0x8d, 0x37,
	0xd8, 0xf6, 0xae, 0x61, 0x9b, 0x44, 0xb1, 0x65, 0x0f, 0x8d, 0x2d, 0x7b, 0xf8, 0x1f, 0xf6, 0x4e,
	0xc9, 0xd1, 0xda, 0xcc, 0x89, 0x28, 0xa0, 0x34, 0x74, 0x44, 0xf6, 0x2e, 0xbc, 0x6a, 0x5a, 0x4f,
	0x77, 0x53, 0xcf, 0xa5, 0x1d, 0x78, 0x0d, 0x5d, 0xdc, 0x37, 0x34, 0xef, 0xf5, 0xa7, 0x57, 0x37,
	0xf9, 0x3c, 0x84, 0xbb, 0x18, 0x78, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x37, 0xb5, 0x2b,
	0x08, 0x05, 0x00, 0x00,
}
