// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidatorSetProto struct {
	Validators           []*ValidatorProto `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	Proposer             *ValidatorProto   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	TotalVotingPower     int64             `protobuf:"varint,3,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ValidatorSetProto) Reset()         { *m = ValidatorSetProto{} }
func (m *ValidatorSetProto) String() string { return proto.CompactTextString(m) }
func (*ValidatorSetProto) ProtoMessage()    {}
func (*ValidatorSetProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{0}
}

func (m *ValidatorSetProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorSetProto.Unmarshal(m, b)
}
func (m *ValidatorSetProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorSetProto.Marshal(b, m, deterministic)
}
func (m *ValidatorSetProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSetProto.Merge(m, src)
}
func (m *ValidatorSetProto) XXX_Size() int {
	return xxx_messageInfo_ValidatorSetProto.Size(m)
}
func (m *ValidatorSetProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSetProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSetProto proto.InternalMessageInfo

func (m *ValidatorSetProto) GetValidators() []*ValidatorProto {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *ValidatorSetProto) GetProposer() *ValidatorProto {
	if m != nil {
		return m.Proposer
	}
	return nil
}

func (m *ValidatorSetProto) GetTotalVotingPower() int64 {
	if m != nil {
		return m.TotalVotingPower
	}
	return 0
}

type ValidatorProto struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	VotingPower          int64    `protobuf:"varint,3,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	ProposerPriority     int64    `protobuf:"varint,4,opt,name=proposer_priority,json=proposerPriority,proto3" json:"proposer_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorProto) Reset()         { *m = ValidatorProto{} }
func (m *ValidatorProto) String() string { return proto.CompactTextString(m) }
func (*ValidatorProto) ProtoMessage()    {}
func (*ValidatorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{1}
}

func (m *ValidatorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorProto.Unmarshal(m, b)
}
func (m *ValidatorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorProto.Marshal(b, m, deterministic)
}
func (m *ValidatorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorProto.Merge(m, src)
}
func (m *ValidatorProto) XXX_Size() int {
	return xxx_messageInfo_ValidatorProto.Size(m)
}
func (m *ValidatorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorProto proto.InternalMessageInfo

func (m *ValidatorProto) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ValidatorProto) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *ValidatorProto) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *ValidatorProto) GetProposerPriority() int64 {
	if m != nil {
		return m.ProposerPriority
	}
	return 0
}

type SimpleValidatorProto struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	VotingPower          int64    `protobuf:"varint,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleValidatorProto) Reset()         { *m = SimpleValidatorProto{} }
func (m *SimpleValidatorProto) String() string { return proto.CompactTextString(m) }
func (*SimpleValidatorProto) ProtoMessage()    {}
func (*SimpleValidatorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{2}
}

func (m *SimpleValidatorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleValidatorProto.Unmarshal(m, b)
}
func (m *SimpleValidatorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleValidatorProto.Marshal(b, m, deterministic)
}
func (m *SimpleValidatorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleValidatorProto.Merge(m, src)
}
func (m *SimpleValidatorProto) XXX_Size() int {
	return xxx_messageInfo_SimpleValidatorProto.Size(m)
}
func (m *SimpleValidatorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleValidatorProto.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleValidatorProto proto.InternalMessageInfo

func (m *SimpleValidatorProto) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *SimpleValidatorProto) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorSetProto)(nil), "tendermint.types.ValidatorSetProto")
	proto.RegisterType((*ValidatorProto)(nil), "tendermint.types.ValidatorProto")
	proto.RegisterType((*SimpleValidatorProto)(nil), "tendermint.types.SimpleValidatorProto")
}

func init() { proto.RegisterFile("validator.proto", fileDescriptor_bf1c6ec7c0d80dd5) }

var fileDescriptor_bf1c6ec7c0d80dd5 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xed, 0x36, 0x36, 0xc9, 0x86, 0x6e, 0x61, 0x60, 0x11, 0xc4, 0xba, 0xd3, 0x40, 0x6d,
	0x41, 0xaf, 0x43, 0x64, 0x57, 0x2f, 0xa3, 0x83, 0x1d, 0xbc, 0x94, 0x66, 0x7d, 0xeb, 0x82, 0xdd,
	0x5e, 0x78, 0x4d, 0x27, 0xfd, 0x28, 0x7e, 0x1c, 0x6f, 0x7e, 0x0a, 0x3f, 0x8b, 0x2c, 0xb5, 0x9d,
	0x4e, 0x05, 0x4f, 0x49, 0xde, 0x3f, 0xbf, 0xf7, 0x7e, 0x24, 0xec, 0x78, 0x13, 0x26, 0x32, 0x0a,
	0x35, 0x92, 0xab, 0x08, 0x35, 0xf2, 0xae, 0x86, 0x75, 0x04, 0xb4, 0x92, 0x6b, 0xed, 0xea, 0x5c,
	0x41, 0x7a, 0xda, 0x8f, 0x31, 0x46, 0x13, 0x7a, 0xdb, 0x5d, 0x71, 0x6f, 0xf0, 0x6a, 0xb1, 0xde,
	0xac, 0x64, 0xa7, 0xa0, 0x27, 0x86, 0xbe, 0x67, 0xac, 0x6a, 0x98, 0xda, 0x96, 0x53, 0x1f, 0xb6,
	0x6f, 0x1c, 0x77, 0xbf, 0xa5, 0x5b, 0x81, 0x86, 0xf2, 0xbf, 0x30, 0x7c, 0xc4, 0x0e, 0x15, 0xa1,
	0xc2, 0x14, 0xc8, 0xae, 0x39, 0xd6, 0xbf, 0xf8, 0x8a, 0xe0, 0x57, 0x8c, 0x6b, 0xd4, 0x61, 0x12,
	0x6c, 0x50, 0xcb, 0x75, 0x1c, 0x28, 0x7c, 0x06, 0xb2, 0xeb, 0x8e, 0x35, 0xac, 0xfb, 0x5d, 0x93,
	0xcc, 0x4c, 0x30, 0xd9, 0xd6, 0x07, 0x2f, 0x16, 0x3b, 0xfa, 0xde, 0x8a, 0xdb, 0xac, 0x15, 0x46,
	0x11, 0x41, 0xba, 0xb5, 0xb7, 0x86, 0x1d, 0xbf, 0x3c, 0xf2, 0x33, 0xd6, 0x52, 0x99, 0x08, 0x9e,
	0x20, 0x37, 0x5e, 0x9d, 0x71, 0xe3, 0xed, 0xfd, 0xfc, 0xc0, 0x6f, 0xaa, 0x4c, 0x3c, 0x40, 0xce,
	0x2f, 0x58, 0xe7, 0x97, 0x99, 0xed, 0xcd, 0x6e, 0x1c, 0xbf, 0x64, 0xbd, 0x52, 0x34, 0x50, 0x24,
	0x91, 0xa4, 0xce, 0xed, 0x46, 0xe1, 0x56, 0x06, 0x93, 0xcf, 0xfa, 0xc0, 0x67, 0xfd, 0xa9, 0x5c,
	0xa9, 0x04, 0xf6, 0x04, 0x4f, 0x76, 0x1a, 0x85, 0xe0, 0x5f, 0x02, 0xb5, 0x1f, 0x02, 0xe3, 0xbb,
	0xc7, 0x51, 0x2c, 0xf5, 0x32, 0x13, 0xee, 0x1c, 0x57, 0xde, 0x32, 0x57, 0x40, 0x09, 0x44, 0x31,
	0x90, 0xb7, 0x08, 0x05, 0xc9, 0xf9, 0x75, 0x44, 0xa8, 0x12, 0x29, 0x3c, 0xf3, 0xc5, 0x69, 0xb1,
	0x88, 0x6c, 0x91, 0x7a, 0xe6, 0xd9, 0x45, 0xd3, 0x14, 0x6e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x84, 0x90, 0x2e, 0xec, 0x35, 0x02, 0x00, 0x00,
}
