// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lifecycle.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LifeCycleDefaultChannelMessageWrapper struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifeCycleDefaultChannelMessageWrapper) Reset()         { *m = LifeCycleDefaultChannelMessageWrapper{} }
func (m *LifeCycleDefaultChannelMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*LifeCycleDefaultChannelMessageWrapper) ProtoMessage()    {}
func (*LifeCycleDefaultChannelMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{0}
}

func (m *LifeCycleDefaultChannelMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper.Unmarshal(m, b)
}
func (m *LifeCycleDefaultChannelMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper.Marshal(b, m, deterministic)
}
func (m *LifeCycleDefaultChannelMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper.Merge(m, src)
}
func (m *LifeCycleDefaultChannelMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper.Size(m)
}
func (m *LifeCycleDefaultChannelMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_LifeCycleDefaultChannelMessageWrapper proto.InternalMessageInfo

type LifeCycleDefaultChannelDataMessageWrapper struct {
	// Types that are valid to be assigned to Sum:
	//	*LifeCycleDefaultChannelDataMessageWrapper_PingMessageProto
	//	*LifeCycleDefaultChannelDataMessageWrapper_PongMessageProto
	//	*LifeCycleDefaultChannelDataMessageWrapper_BroadcastMessageProto
	//	*LifeCycleDefaultChannelDataMessageWrapper_MemberInfoBroadcastMessageProto
	Sum                  isLifeCycleDefaultChannelDataMessageWrapper_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) Reset() {
	*m = LifeCycleDefaultChannelDataMessageWrapper{}
}
func (m *LifeCycleDefaultChannelDataMessageWrapper) String() string {
	return proto.CompactTextString(m)
}
func (*LifeCycleDefaultChannelDataMessageWrapper) ProtoMessage() {}
func (*LifeCycleDefaultChannelDataMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{1}
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper.Unmarshal(m, b)
}
func (m *LifeCycleDefaultChannelDataMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper.Marshal(b, m, deterministic)
}
func (m *LifeCycleDefaultChannelDataMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper.Merge(m, src)
}
func (m *LifeCycleDefaultChannelDataMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper.Size(m)
}
func (m *LifeCycleDefaultChannelDataMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_LifeCycleDefaultChannelDataMessageWrapper proto.InternalMessageInfo

type isLifeCycleDefaultChannelDataMessageWrapper_Sum interface {
	isLifeCycleDefaultChannelDataMessageWrapper_Sum()
}

type LifeCycleDefaultChannelDataMessageWrapper_PingMessageProto struct {
	PingMessageProto *PingMessageProto `protobuf:"bytes,1,opt,name=ping_message_proto,json=pingMessageProto,proto3,oneof"`
}

type LifeCycleDefaultChannelDataMessageWrapper_PongMessageProto struct {
	PongMessageProto *PongMessageProto `protobuf:"bytes,2,opt,name=pong_message_proto,json=pongMessageProto,proto3,oneof"`
}

type LifeCycleDefaultChannelDataMessageWrapper_BroadcastMessageProto struct {
	BroadcastMessageProto *PingPongBroadCastMessageProto `protobuf:"bytes,3,opt,name=broadcast_message_proto,json=broadcastMessageProto,proto3,oneof"`
}

type LifeCycleDefaultChannelDataMessageWrapper_MemberInfoBroadcastMessageProto struct {
	MemberInfoBroadcastMessageProto *MemberInfoBroadCastMessageProto `protobuf:"bytes,4,opt,name=member_info_broadcast_message_proto,json=memberInfoBroadcastMessageProto,proto3,oneof"`
}

func (*LifeCycleDefaultChannelDataMessageWrapper_PingMessageProto) isLifeCycleDefaultChannelDataMessageWrapper_Sum() {
}

func (*LifeCycleDefaultChannelDataMessageWrapper_PongMessageProto) isLifeCycleDefaultChannelDataMessageWrapper_Sum() {
}

func (*LifeCycleDefaultChannelDataMessageWrapper_BroadcastMessageProto) isLifeCycleDefaultChannelDataMessageWrapper_Sum() {
}

func (*LifeCycleDefaultChannelDataMessageWrapper_MemberInfoBroadcastMessageProto) isLifeCycleDefaultChannelDataMessageWrapper_Sum() {
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) GetSum() isLifeCycleDefaultChannelDataMessageWrapper_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) GetPingMessageProto() *PingMessageProto {
	if x, ok := m.GetSum().(*LifeCycleDefaultChannelDataMessageWrapper_PingMessageProto); ok {
		return x.PingMessageProto
	}
	return nil
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) GetPongMessageProto() *PongMessageProto {
	if x, ok := m.GetSum().(*LifeCycleDefaultChannelDataMessageWrapper_PongMessageProto); ok {
		return x.PongMessageProto
	}
	return nil
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) GetBroadcastMessageProto() *PingPongBroadCastMessageProto {
	if x, ok := m.GetSum().(*LifeCycleDefaultChannelDataMessageWrapper_BroadcastMessageProto); ok {
		return x.BroadcastMessageProto
	}
	return nil
}

func (m *LifeCycleDefaultChannelDataMessageWrapper) GetMemberInfoBroadcastMessageProto() *MemberInfoBroadCastMessageProto {
	if x, ok := m.GetSum().(*LifeCycleDefaultChannelDataMessageWrapper_MemberInfoBroadcastMessageProto); ok {
		return x.MemberInfoBroadcastMessageProto
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LifeCycleDefaultChannelDataMessageWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LifeCycleDefaultChannelDataMessageWrapper_PingMessageProto)(nil),
		(*LifeCycleDefaultChannelDataMessageWrapper_PongMessageProto)(nil),
		(*LifeCycleDefaultChannelDataMessageWrapper_BroadcastMessageProto)(nil),
		(*LifeCycleDefaultChannelDataMessageWrapper_MemberInfoBroadcastMessageProto)(nil),
	}
}

type PingPongBroadCastMessageProto struct {
	// 包含了端口号,ip等信息
	// info: /tcp/ip/端口号/
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPongBroadCastMessageProto) Reset()         { *m = PingPongBroadCastMessageProto{} }
func (m *PingPongBroadCastMessageProto) String() string { return proto.CompactTextString(m) }
func (*PingPongBroadCastMessageProto) ProtoMessage()    {}
func (*PingPongBroadCastMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{2}
}

func (m *PingPongBroadCastMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPongBroadCastMessageProto.Unmarshal(m, b)
}
func (m *PingPongBroadCastMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPongBroadCastMessageProto.Marshal(b, m, deterministic)
}
func (m *PingPongBroadCastMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongBroadCastMessageProto.Merge(m, src)
}
func (m *PingPongBroadCastMessageProto) XXX_Size() int {
	return xxx_messageInfo_PingPongBroadCastMessageProto.Size(m)
}
func (m *PingPongBroadCastMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongBroadCastMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongBroadCastMessageProto proto.InternalMessageInfo

func (m *PingPongBroadCastMessageProto) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type PingMessageProto struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessageProto) Reset()         { *m = PingMessageProto{} }
func (m *PingMessageProto) String() string { return proto.CompactTextString(m) }
func (*PingMessageProto) ProtoMessage()    {}
func (*PingMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{3}
}

func (m *PingMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessageProto.Unmarshal(m, b)
}
func (m *PingMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessageProto.Marshal(b, m, deterministic)
}
func (m *PingMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessageProto.Merge(m, src)
}
func (m *PingMessageProto) XXX_Size() int {
	return xxx_messageInfo_PingMessageProto.Size(m)
}
func (m *PingMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessageProto proto.InternalMessageInfo

func (m *PingMessageProto) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PongMessageProto struct {
	Pong                 string   `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongMessageProto) Reset()         { *m = PongMessageProto{} }
func (m *PongMessageProto) String() string { return proto.CompactTextString(m) }
func (*PongMessageProto) ProtoMessage()    {}
func (*PongMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{4}
}

func (m *PongMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongMessageProto.Unmarshal(m, b)
}
func (m *PongMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongMessageProto.Marshal(b, m, deterministic)
}
func (m *PongMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongMessageProto.Merge(m, src)
}
func (m *PongMessageProto) XXX_Size() int {
	return xxx_messageInfo_PongMessageProto.Size(m)
}
func (m *PongMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PongMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_PongMessageProto proto.InternalMessageInfo

func (m *PongMessageProto) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

/////////////////////// member
type MemberInfoBroadCastMessageProto struct {
	Members              []*MemberInfoNodeMessageProto `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MemberInfoBroadCastMessageProto) Reset()         { *m = MemberInfoBroadCastMessageProto{} }
func (m *MemberInfoBroadCastMessageProto) String() string { return proto.CompactTextString(m) }
func (*MemberInfoBroadCastMessageProto) ProtoMessage()    {}
func (*MemberInfoBroadCastMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{5}
}

func (m *MemberInfoBroadCastMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoBroadCastMessageProto.Unmarshal(m, b)
}
func (m *MemberInfoBroadCastMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoBroadCastMessageProto.Marshal(b, m, deterministic)
}
func (m *MemberInfoBroadCastMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoBroadCastMessageProto.Merge(m, src)
}
func (m *MemberInfoBroadCastMessageProto) XXX_Size() int {
	return xxx_messageInfo_MemberInfoBroadCastMessageProto.Size(m)
}
func (m *MemberInfoBroadCastMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoBroadCastMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoBroadCastMessageProto proto.InternalMessageInfo

func (m *MemberInfoBroadCastMessageProto) GetMembers() []*MemberInfoNodeMessageProto {
	if m != nil {
		return m.Members
	}
	return nil
}

type MemberInfoNodeMessageProto struct {
	ExternMultiAddress   string   `protobuf:"bytes,1,opt,name=extern_multi_address,json=externMultiAddress,proto3" json:"extern_multi_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberInfoNodeMessageProto) Reset()         { *m = MemberInfoNodeMessageProto{} }
func (m *MemberInfoNodeMessageProto) String() string { return proto.CompactTextString(m) }
func (*MemberInfoNodeMessageProto) ProtoMessage()    {}
func (*MemberInfoNodeMessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_84f7c7eee8484930, []int{6}
}

func (m *MemberInfoNodeMessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberInfoNodeMessageProto.Unmarshal(m, b)
}
func (m *MemberInfoNodeMessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberInfoNodeMessageProto.Marshal(b, m, deterministic)
}
func (m *MemberInfoNodeMessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberInfoNodeMessageProto.Merge(m, src)
}
func (m *MemberInfoNodeMessageProto) XXX_Size() int {
	return xxx_messageInfo_MemberInfoNodeMessageProto.Size(m)
}
func (m *MemberInfoNodeMessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberInfoNodeMessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_MemberInfoNodeMessageProto proto.InternalMessageInfo

func (m *MemberInfoNodeMessageProto) GetExternMultiAddress() string {
	if m != nil {
		return m.ExternMultiAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*LifeCycleDefaultChannelMessageWrapper)(nil), "protocols.p2p.LifeCycleDefaultChannelMessageWrapper")
	proto.RegisterType((*LifeCycleDefaultChannelDataMessageWrapper)(nil), "protocols.p2p.LifeCycleDefaultChannelDataMessageWrapper")
	proto.RegisterType((*PingPongBroadCastMessageProto)(nil), "protocols.p2p.PingPongBroadCastMessageProto")
	proto.RegisterType((*PingMessageProto)(nil), "protocols.p2p.PingMessageProto")
	proto.RegisterType((*PongMessageProto)(nil), "protocols.p2p.PongMessageProto")
	proto.RegisterType((*MemberInfoBroadCastMessageProto)(nil), "protocols.p2p.MemberInfoBroadCastMessageProto")
	proto.RegisterType((*MemberInfoNodeMessageProto)(nil), "protocols.p2p.MemberInfoNodeMessageProto")
}

func init() { proto.RegisterFile("lifecycle.proto", fileDescriptor_84f7c7eee8484930) }

var fileDescriptor_84f7c7eee8484930 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0xad, 0x59, 0x15, 0x67, 0x11, 0x97, 0x41, 0x71, 0x11, 0xa4, 0x4b, 0x44, 0xdd, 0x05,
	0x4d, 0xa4, 0x45, 0x7c, 0xb6, 0xe9, 0x83, 0x82, 0xad, 0xa5, 0x2f, 0x82, 0x2f, 0x61, 0x92, 0xdc,
	0x49, 0x07, 0xe6, 0x1f, 0x33, 0x13, 0xb0, 0x2f, 0x7e, 0x32, 0x3f, 0x9c, 0xcc, 0xa4, 0x95, 0x26,
	0x26, 0xee, 0x53, 0x86, 0x7b, 0x7f, 0xf7, 0x9c, 0x73, 0x73, 0xd1, 0x63, 0xce, 0x28, 0x94, 0xfb,
	0x92, 0x43, 0xa2, 0x8d, 0x72, 0x0a, 0x3f, 0x0a, 0x9f, 0x52, 0x71, 0x9b, 0xe8, 0x99, 0x8e, 0xdf,
	0xa0, 0x57, 0x5f, 0x19, 0x85, 0xcc, 0x13, 0x4b, 0xa0, 0xa4, 0xe1, 0x2e, 0xdb, 0x11, 0x29, 0x81,
	0xaf, 0xc0, 0x5a, 0x52, 0xc3, 0x77, 0x43, 0xb4, 0x06, 0x13, 0xff, 0x8e, 0xd0, 0xcd, 0x08, 0xb9,
	0x24, 0x8e, 0x74, 0x69, 0xfc, 0x0d, 0x61, 0xcd, 0x64, 0x9d, 0x8b, 0xb6, 0x9c, 0x07, 0xd3, 0xcb,
	0xc9, 0xd5, 0xe4, 0xfa, 0x7c, 0x36, 0x4d, 0x3a, 0x11, 0x92, 0x0d, 0x93, 0xf5, 0x61, 0x7c, 0xe3,
	0x1b, 0x9f, 0xef, 0x6c, 0x2f, 0x74, 0xaf, 0x16, 0x04, 0xd5, 0x3f, 0x82, 0x77, 0x87, 0x05, 0xd5,
	0x80, 0x60, 0xaf, 0x86, 0x29, 0x7a, 0x56, 0x18, 0x45, 0xaa, 0x92, 0x58, 0xd7, 0x53, 0x8d, 0x82,
	0xea, 0xdb, 0x81, 0x98, 0x5e, 0x79, 0xe1, 0xa7, 0x32, 0x62, 0x5d, 0xcf, 0xe2, 0xe9, 0x5f, 0xb9,
	0x8e, 0xcf, 0x2f, 0xf4, 0x52, 0x80, 0x28, 0xc0, 0xe4, 0x4c, 0x52, 0x95, 0x8f, 0x79, 0x9e, 0x05,
	0xcf, 0xa4, 0xe7, 0xb9, 0x0a, 0x93, 0x5f, 0x24, 0x55, 0x63, 0xae, 0x53, 0xd1, 0x45, 0xfa, 0xfe,
	0x8b, 0x7b, 0x28, 0xb2, 0x8d, 0x88, 0xe7, 0xe8, 0xc5, 0x7f, 0x17, 0xc0, 0x18, 0x9d, 0xf9, 0x80,
	0xe1, 0x46, 0x0f, 0xb7, 0xe1, 0x1d, 0xbf, 0x46, 0x17, 0xfd, 0xe3, 0x78, 0xce, 0x1f, 0xe7, 0xc8,
	0xf9, 0x77, 0xe0, 0xd4, 0x00, 0xa7, 0x4e, 0x38, 0x25, 0xeb, 0x98, 0xa2, 0xe9, 0x2d, 0x1b, 0xe1,
	0x0c, 0x3d, 0x68, 0x37, 0xb2, 0x97, 0x93, 0xab, 0xe8, 0xfa, 0x7c, 0x76, 0x33, 0xfa, 0x4b, 0xd6,
	0xaa, 0x82, 0xd3, 0xd9, 0xed, 0x71, 0x32, 0x5e, 0xa3, 0xe7, 0xe3, 0x18, 0x7e, 0x8f, 0x9e, 0xc0,
	0x4f, 0x07, 0x46, 0xe6, 0xa2, 0xe1, 0x8e, 0xe5, 0xa4, 0xaa, 0x0c, 0x58, 0x7b, 0x48, 0x8a, 0xdb,
	0xde, 0xca, 0xb7, 0x3e, 0xb5, 0x9d, 0xc5, 0xc7, 0x1f, 0x1f, 0x6a, 0xe6, 0x76, 0x4d, 0x91, 0x94,
	0x4a, 0xa4, 0xbb, 0xbd, 0x06, 0xc3, 0xa1, 0xaa, 0xc1, 0xa4, 0x94, 0x14, 0x86, 0x95, 0xef, 0x2a,
	0xa3, 0x34, 0x67, 0x45, 0xea, 0xc0, 0x08, 0x26, 0x09, 0x4f, 0x43, 0x66, 0x5b, 0xdc, 0x0f, 0xdf,
	0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xf4, 0xe7, 0xb8, 0x86, 0x03, 0x00, 0x00,
}
